(function(){function g(a){throw a;}var i=true,j=null,k=false,aa=Error,ba=Boolean,ca=undefined,da=encodeURIComponent,ea=parseInt,fa=parseFloat,ha=String,l=window,m=Object,ia=document,ja=decodeURIComponent,o=Math;function ka(a,b){return a.toString=b}function la(a,b){return a.length=b}function ma(a,b){return a.className=b}function na(a,b){return a.width=b}function oa(a,b){return a.cancel=b}function pa(a,b){return a.innerHTML=b}function qa(a,b){return a.value=b}function ra(a,b){return a.currentTarget=b}
function ta(a,b){return a.left=b}function ua(a,b){return a.target=b}function va(a,b){return a.send=b}function wa(a,b){return a.isAvailable=b}function xa(a,b){return a.bottom=b}function ya(a,b){return a.href=b}function za(a,b){return a.contains=b}function Aa(a,b){return a.display=b}function Ba(a,b){return a.height=b}function Ca(a,b){return a.right=b}
var p="appendChild",Da="scrollTop",Ea="previousSibling",s="push",v="toString",x="length",Fa="propertyIsEnumerable",Ga="getBoundingClientRect",y="prototype",Ha="test",Ia="shift",Ja="sourceIndex",Ka="className",La="clearTimeout",z="width",Ma="index",Na="text",Oa="clientWidth",Pa="cancel",Qa="round",Ra="slice",Sa="setTimeout",A="replace",B="nodeType",Ta="document",Ua="split",Va="offsetWidth",Wa="createTextNode",Xa="value",Ya="location",Za="item",$a="insertBefore",C="indexOf",ab="hasOwnProperty",bb="compareDocumentPosition",
cb="dispatchEvent",D="style",db="close",eb="nodeName",fb="currentTarget",E="body",F="left",gb="write",hb="ownerDocument",ib="removeChild",jb="target",kb="screenX",lb="screenY",mb="lastChild",G="call",nb="getBoxObjectFor",ob="send",H="createElement",pb="scrollHeight",qb="keyCode",I="firstChild",rb="forEach",sb="isAvailable",tb="clientHeight",ub="scrollLeft",vb="clientLeft",J="bottom",wb="currentStyle",xb="href",yb="substring",zb="clientTop",Ab="handleEvent",Bb="removeNode",Cb="restore",Db="type",Eb=
"contains",Fb="apply",Gb="childNodes",K="tagName",Hb="setPosition",Ib="defaultView",L="parentNode",Jb="nextSibling",Kb="contentWindow",M="height",Lb="offsetHeight",N="join",Mb="unshift",Nb="nodeValue",Ob="documentElement",O="right";function Pb(a){return function(){return this[a]}}var P,Q=this;function Qb(a,b,c){a=a[Ua](".");c=c||Q;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[x]&&(d=a[Ia]());)if(!a[x]&&b!==ca)c[d]=b;else c=c[d]?c[d]:(c[d]={})}
function Rb(a,b){a=a[Ua](".");b=b||Q;for(var c;c=a[Ia]();)if(b[c])b=b[c];else return j;return b}function Sb(){}function Tb(a){a.sc=function(){return a.a||(a.a=new a)}}
function Ub(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof m)&&m[y][v][G](a)=="[object Array]"||typeof a[x]=="number"&&typeof a.splice!="undefined"&&typeof a[Fa]!="undefined"&&!a[Fa]("splice"))return"array";if(!(a instanceof m)&&(m[y][v][G](a)=="[object Function]"||typeof a[G]!="undefined"&&typeof a[Fa]!="undefined"&&!a[Fa]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[G]=="undefined")return"object";return b}
function R(a){return Ub(a)=="array"}function Vb(a){var b=Ub(a);return b=="array"||b=="object"&&typeof a[x]=="number"}function S(a){return typeof a=="string"}function Wb(a){return Ub(a)=="function"}function Xb(a){a=Ub(a);return a=="object"||a=="array"||a=="function"}function Yb(a){if(a[ab]&&a[ab](Zb))return a[Zb];a[Zb]||(a[Zb]=++$b);return a[Zb]}var Zb="closure_hashCode_"+o.floor(o.random()*2147483648)[v](36),$b=0;
function ac(a){var b=Ub(a);if(b=="object"||b=="array"){if(a.L)return a.L[G](a);b=b=="array"?[]:{};for(var c in a)b[c]=ac(a[c]);return b}return a}function T(a,b){var c=b||Q;if(arguments[x]>2){var d=Array[y][Ra][G](arguments,2);return function(){var e=Array[y][Ra][G](arguments);Array[y][Mb][Fb](e,d);return a[Fb](c,e)}}else return function(){return a[Fb](c,arguments)}}
function bc(a){var b=Array[y][Ra][G](arguments,1);return function(){var c=Array[y][Ra][G](arguments);c[Mb][Fb](c,b);return a[Fb](this,c)}}var cc=Date.now||function(){return+new Date};function U(a,b){function c(){}c.prototype=b[y];a.A=b[y];a.prototype=new c};var dc=google.translate._const,ec=dc._cl||"en",fc=dc._cuc,gc=dc._cnad||k,hc=dc._cnal||{},ic=dc._cac||"te",jc=dc._pbi||"",kc=dc._pci||"",lc=dc._phf||"",mc=dc._plla||"",nc=dc._pli||"",oc=dc._pmi||"",pc=dc._ps||"",qc=dc._puh||"",rc=l[Ya].protocol=="https:"?"https://":"http://",sc=rc+"www.google.com/images/cleardot.gif",tc=rc+"www.google.com/intl/"+ec[A]("_","-")+"/images/logos/translate_logo_sm_trans.gif";function uc(){}uc[y].Yb=k;uc[y].t=function(){if(!this.Yb){this.Yb=i;this.D()}};uc[y].D=function(){};var vc=Array[y],wc=vc[C]?function(a,b,c){return vc[C][G](a,b,c)}:function(a,b,c){c=c==j?0:c<0?o.max(0,a[x]+c):c;if(S(a)){if(!S(b)||b[x]!=1)return-1;return a[C](b,c)}for(c=c;c<a[x];c++)if(c in a&&a[c]===b)return c;return-1},xc=vc[rb]?function(a,b,c){vc[rb][G](a,b,c)}:function(a,b,c){for(var d=a[x],e=S(a)?a[Ua](""):a,f=0;f<d;f++)f in e&&b[G](c,e[f],f,a)};function yc(a,b){return wc(a,b)>=0}function zc(a,b){b=wc(a,b);var c;if(c=b>=0)vc.splice[G](a,b,1)[x]==1;return c}
function Ac(){return vc.concat[Fb](vc,arguments)}function Bc(a){if(R(a))return Ac(a);else{for(var b=[],c=0,d=a[x];c<d;c++)b[c]=a[c];return b}}function Cc(a){for(var b=1;b<arguments[x];b++){var c=arguments[b],d;if(R(c)||(d=Vb(c))&&c[ab]("callee"))a[s][Fb](a,c);else if(d)for(var e=a[x],f=c[x],h=0;h<f;h++)a[e+h]=c[h];else a[s](c)}}function Dc(a){return vc.splice[Fb](a,Ec(arguments,1))}function Ec(a,b,c){return arguments[x]<=2?vc[Ra][G](a,b):vc[Ra][G](a,b,c)};function Fc(a,b){this.x=a!==ca?a:0;this.y=b!==ca?b:0}Fc[y].L=function(){return new Fc(this.x,this.y)};ka(Fc[y],function(){return"("+this.x+", "+this.y+")"});function Gc(a,b){return new Fc(a.x-b.x,a.y-b.y)};function Hc(a,b){na(this,a);Ba(this,b)}Hc[y].L=function(){return new Hc(this[z],this[M])};ka(Hc[y],function(){return"("+this[z]+" x "+this[M]+")"});Hc[y].floor=function(){na(this,o.floor(this[z]));Ba(this,o.floor(this[M]));return this};Hc[y].round=function(){na(this,o[Qa](this[z]));Ba(this,o[Qa](this[M]));return this};function Ic(a,b,c){for(var d in a)b[G](c,a[d],d,a)}function Jc(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function Kc(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function Lc(a,b){var c;if(c=b in a)delete a[b];return c}function Mc(a,b,c){if(b in a)return a[b];return c}var Nc=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function Oc(a){for(var b,c,d=1;d<arguments[x];d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<Nc[x];e++){b=Nc[e];if(m[y][ab][G](c,b))a[b]=c[b]}}};function Pc(a){return a[A](/^[\s\xa0]+|[\s\xa0]+$/g,"")}function Qc(a){return a[A](/^[\s\xa0]+/,"")}function Rc(a){return a[A](/[\s\xa0]+$/,"")}var Sc=/^[a-zA-Z0-9\-_.!~*'()]*$/;function Tc(a){a=ha(a);if(!Sc[Ha](a))return da(a);return a}
function Uc(a,b){if(b)return a[A](Vc,"&amp;")[A](Wc,"&lt;")[A](Xc,"&gt;")[A](Yc,"&quot;");else{if(!Zc[Ha](a))return a;if(a[C]("&")!=-1)a=a[A](Vc,"&amp;");if(a[C]("<")!=-1)a=a[A](Wc,"&lt;");if(a[C](">")!=-1)a=a[A](Xc,"&gt;");if(a[C]('"')!=-1)a=a[A](Yc,"&quot;");return a}}var Vc=/&/g,Wc=/</g,Xc=/>/g,Yc=/\"/g,Zc=/[&<>\"]/;function $c(a){if(a[C]("&")!=-1)return"document"in Q&&a[C]("<")==-1?ad(a):bd(a);return a}
function ad(a){var b=Q[Ta][H]("a");pa(b,a);b.normalize&&b.normalize();a=b[I][Nb];pa(b,"");return a}function bd(a){return a[A](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){c=Number("0"+c.substr(1));if(!isNaN(c))return ha.fromCharCode(c)}return b}})}
function cd(a,b){var c=0;a=Pc(ha(a))[Ua](".");b=Pc(ha(b))[Ua](".");for(var d=o.max(a[x],b[x]),e=0;c==0&&e<d;e++){var f=a[e]||"",h=b[e]||"",n=new RegExp("(\\d*)(\\D*)","g"),q=new RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(f)||["","",""],t=q.exec(h)||["","",""];if(r[0][x]==0&&t[0][x]==0)break;c=r[1][x]==0?0:ea(r[1],10);var w=t[1][x]==0?0:ea(t[1],10);c=dd(c,w)||dd(r[2][x]==0,t[2][x]==0)||dd(r[2],t[2])}while(c==0)}return c}function dd(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}cc();var ed,fd,gd,hd,id,jd,kd,ld,md;function nd(){return Q.navigator?Q.navigator.userAgent:j}function od(){return Q.navigator}id=hd=gd=fd=ed=k;var pd;if(pd=nd()){var qd=od();ed=pd[C]("Opera")==0;fd=!ed&&pd[C]("MSIE")!=-1;hd=(gd=!ed&&pd[C]("WebKit")!=-1)&&pd[C]("Mobile")!=-1;id=!ed&&!gd&&qd.product=="Gecko"}var rd=ed,V=fd,sd=id,td=gd,ud=hd,vd,wd=od(),xd=vd=wd&&wd.platform||"";jd=xd[C]("Mac")!=-1;kd=xd[C]("Win")!=-1;ld=xd[C]("Linux")!=-1;md=!!od()&&(od().appVersion||"")[C]("X11")!=-1;
var yd=jd,zd=md,Ad,Bd="",Cd;if(rd&&Q.opera){var Dd=Q.opera.version;Bd=typeof Dd=="function"?Dd():Dd}else{if(sd)Cd=/rv\:([^\);]+)(\)|;)/;else if(V)Cd=/MSIE\s+([^\);]+)(\)|;)/;else if(td)Cd=/WebKit\/(\S+)/;if(Cd){var Ed=Cd.exec(nd());Bd=Ed?Ed[1]:""}}var Fd=Ad=Bd,Gd={};function Hd(a){return Gd[a]||(Gd[a]=cd(Fd,a)>=0)};var W={};W.n={};W.n.ea=function(a,b){ma(a,b)};W.n.N=function(a){return(a=a[Ka])&&typeof a[Ua]=="function"?a[Ua](/\s+/):[]};W.n.add=function(a){var b=W.n.N(a),c=Ec(arguments,1);c=W.n.bc(b,c);ma(a,b[N](" "));return c};W.n.remove=function(a){var b=W.n.N(a),c=Ec(arguments,1);c=W.n.Lc(b,c);ma(a,b[N](" "));return c};W.n.bc=function(a,b){for(var c=0,d=0;d<b[x];d++)if(!yc(a,b[d])){a[s](b[d]);c++}return c==b[x]};W.n.Lc=function(a,b){for(var c=0,d=0;d<a[x];d++)if(yc(b,a[d])){Dc(a,d--,1);c++}return c==b[x]};
W.n.we=function(a,b,c){for(var d=W.n.N(a),e=k,f=0;f<d[x];f++)if(d[f]==b){Dc(d,f--,1);e=i}if(e){d[s](c);ma(a,d[N](" "))}return e};W.n.ke=function(a,b,c){var d=W.n.N(a);if(S(b))zc(d,b);else R(b)&&W.n.Lc(d,b);if(S(c)&&!yc(d,c))d[s](c);else R(c)&&W.n.bc(d,c);ma(a,d[N](" "))};W.n.ra=function(a,b){return yc(W.n.N(a),b)};W.n.ed=function(a,b,c){c?W.n.add(a,b):W.n.remove(a,b)};W.n.xe=function(a,b){var c=!W.n.ra(a,b);W.n.ed(a,b,c);return c};var Id="A",Jd="B",Kd="I",Ld="Q",Md="S",Nd="U";W.Rc=k;W.Zb=k;W.Sc=W.Rc||W.Zb;W.P=function(a){return a?new Od(W.Q(a)):W.ad||(W.ad=new Od)};W.o=function(){return ia};W.l=function(a){return S(a)?ia.getElementById(a):a};W.Xb=W.l;W.Va=function(a,b,c){return W.qc(ia,a,b,c)};
W.qc=function(a,b,c,d){d=d||a;b=b&&b!="*"?b.toUpperCase():"";if(d.querySelectorAll&&(b||c)&&(!td||W.Da(a)||Hd("528"))){c=b+(c?"."+c:"");return d.querySelectorAll(c)}if(c&&d.getElementsByClassName){a=d.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)if(b==h[eb])d[e++]=h;la(d,e);return d}else return a}a=d.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++){b=h[Ka];if(typeof b[Ua]=="function"&&yc(b[Ua](/\s+/),c))d[e++]=h}la(d,e);return d}else return a};W.Pc=W.Va;
W.pb=function(a,b){Ic(b,function(c,d){if(d=="style")a[D].cssText=c;else if(d=="class")ma(a,c);else if(d=="for")a.htmlFor=c;else if(d in W.$b)a.setAttribute(W.$b[d],c);else a[d]=c})};W.$b={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};W.Hb=function(a){return W.Bc(a||l)};
W.Bc=function(a){var b=a[Ta];if(td&&!Hd("500")&&!ud){if(typeof a.innerHeight=="undefined")a=l;b=a.innerHeight;var c=a[Ta][Ob][pb];if(a==a.top)if(c<b)b-=15;return new Hc(a.innerWidth,b)}a=W.Da(b)&&(!rd||rd&&Hd("9.50"))?b[Ob]:b[E];return new Hc(a[Oa],a[tb])};W.ld=function(){return W.nc(l)};W.nc=function(a){var b=a[Ta],c=0;if(b){a=W.Bc(a)[M];c=b[E];var d=b[Ob];if(W.Da(b)&&d[pb])c=d[pb]!=a?d[pb]:d[Lb];else{b=d[pb];var e=d[Lb];if(d[tb]!=e){b=c[pb];e=c[Lb]}c=b>a?b>e?b:e:b<e?b:e}}return c};
W.re=function(a){a=a||Q||l;return W.P(a[Ta]).xa()};W.xa=function(){return W.pc(ia)};W.pc=function(a){a=W.Eb(a);return new Fc(a[ub],a[Da])};W.oc=function(){return W.Eb(ia)};W.Eb=function(a){return!td&&W.Da(a)?a[Ob]:a[E]};W.Xa=function(a){return a?W.Ib(a):l};W.Ib=function(a){return a.parentWindow||a[Ib]};W.z=function(){return W.fc(ia,arguments)};
W.fc=function(a,b){var c=b[0],d=b[1];if(V&&d&&(d.name||d[Db])){c=["<",c];d.name&&c[s](' name="',Uc(d.name),'"');if(d[Db]){c[s](' type="',Uc(d[Db]),'"');d=ac(d);delete d[Db]}c[s](">");c=c[N]("")}var e=a[H](c);if(d)if(S(d))ma(e,d);else W.pb(e,d);if(b[x]>2){d=function(h){if(h)e[p](S(h)?a[Wa](h):h)};for(c=2;c<b[x];c++){var f=b[c];Vb(f)&&!W.Pb(f)?xc(W.Dd(f)?Bc(f):f,d):d(f)}}return e};W.Qc=W.z;W.createElement=function(a){return ia[H](a)};W.createTextNode=function(a){return ia[Wa](a)};
W.$c=function(a,b,c){return W.gc(ia,a,b,!!c)};W.gc=function(a,b,c,d){for(var e=["<tr>"],f=0;f<c;f++)e[s](d?"<td>&nbsp;</td>":"<td></td>");e[s]("</tr>");e=e[N]("");c=["<table>"];for(f=0;f<b;f++)c[s](e);c[s]("</table>");a=a[H]("DIV");pa(a,c[N](""));return a[ib](a[I])};W.Cd=function(a){return W.Gc(ia,a)};W.Gc=function(a,b){var c=a[H]("div");pa(c,b);if(c[Gb][x]==1)return c[ib](c[I]);else{for(a=a.createDocumentFragment();c[I];)a[p](c[I]);return a}};W.kd=function(){return W.Ca()?"CSS1Compat":"BackCompat"};
W.Ca=function(){return W.Da(ia)};W.Da=function(a){if(W.Sc)return W.Zb;return a.compatMode=="CSS1Compat"};W.canHaveChildren=function(a){if(a[B]!=1)return k;if("canHaveChildren"in a)return a.canHaveChildren;switch(a[K]){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "STYLE":return k}return i};
W.appendChild=function(a,b){a[p](b)};W.Ia=function(a){for(var b;b=a[I];)a[ib](b)};W.Ob=function(a,b){b[L]&&b[L][$a](a,b)};W.Nb=function(a,b){b[L]&&b[L][$a](a,b[Jb])};W.removeNode=function(a){return a&&a[L]?a[L][ib](a):j};W.replaceNode=function(a,b){var c=b[L];c&&c.replaceChild(a,b)};W.Cb=function(a){var b,c=a[L];if(c&&c[B]!=11)if(a[Bb])return a[Bb](k);else{for(;b=a[I];)c[$a](b,a);return W[Bb](a)}};W.rc=function(a){return W.kb(a[I],i)};W.uc=function(a){return W.kb(a[mb],k)};
W.vc=function(a){return W.kb(a[Jb],i)};W.zc=function(a){return W.kb(a[Ea],k)};W.kb=function(a,b){for(;a&&a[B]!=1;)a=b?a[Jb]:a[Ea];return a};W.wc=function(a){if(!a)return j;if(a[I])return a[I];for(;a&&!a[Jb];)a=a[L];return a?a[Jb]:j};W.Ac=function(a){if(!a)return j;if(!a[Ea])return a[L];for(a=a[Ea];a&&a[mb];)a=a[mb];return a};W.Pb=function(a){return Xb(a)&&a[B]>0};
za(W,function(a,b){if(a[Eb]&&b[B]==1)return a==b||a[Eb](b);if(typeof a[bb]!="undefined")return a==b||ba(a[bb](b)&16);for(;b&&a!=b;)b=b[L];return b==a});
W.ne=function(a,b){if(a==b)return 0;if(a[bb])return a[bb](b)&2?1:-1;if("sourceIndex"in a||a[L]&&"sourceIndex"in a[L]){var c=a[B]==1,d=b[B]==1;if(c&&d)return a[Ja]-b[Ja];else{var e=a[L],f=b[L];if(e==f)return W.dc(a,b);if(!c&&W[Eb](e,b))return-1*W.cc(a,b);if(!d&&W[Eb](f,a))return W.cc(b,a);return(c?a[Ja]:e[Ja])-(d?b[Ja]:f[Ja])}}d=W.Q(a);c=d.createRange();c.selectNode(a);c.collapse(i);a=d.createRange();a.selectNode(b);a.collapse(i);return c.compareBoundaryPoints(Q.Range.START_TO_END,a)};
W.cc=function(a,b){var c=a[L];if(c==b)return-1;for(b=b;b[L]!=c;)b=b[L];return W.dc(b,a)};W.dc=function(a,b){for(b=b;b=b[Ea];)if(b==a)return-1;return 1};W.oe=function(){var a,b=arguments[x];if(b){if(b==1)return arguments[0]}else return j;var c=[],d=Infinity;for(a=0;a<b;a++){for(var e=[],f=arguments[a];f;){e[Mb](f);f=f[L]}c[s](e);d=o.min(d,e[x])}e=j;for(a=0;a<d;a++){f=c[0][a];for(var h=1;h<b;h++)if(f!=c[h][a])return e;e=f}return e};W.Q=function(a){return a[B]==9?a:a[hb]||a[Ta]};
W.Z=function(a){return a=td?a[Ta]||a[Kb][Ta]:a.contentDocument||a[Kb][Ta]};W.Wa=function(a){return a[Kb]||W.Ib(W.Z(a))};W.na=function(a,b){if("textContent"in a)a.textContent=b;else if(a[I]&&a[I][B]==3){for(;a[mb]!=a[I];)a[ib](a[mb]);a[I].data=b}else{W.Ia(a);var c=W.Q(a);a[p](c[Wa](b))}};W.qe=function(a){if("outerHTML"in a)return a.outerHTML;else{var b=W.Q(a);b=b[H]("div");b[p](a.cloneNode(i));return b.innerHTML}};W.kc=function(a,b){var c=[];return(a=W.Bb(a,b,c,i))?c[0]:ca};
W.lc=function(a,b){var c=[];W.Bb(a,b,c,k);return c};W.Bb=function(a,b,c,d){if(a!=j)for(var e=0,f;f=a[Gb][e];e++){if(b(f)){c[s](f);if(d)return i}if(W.Bb(f,b,c,d))return i}return k};W.ac={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};W.eb={IMG:" ",BR:"\n"};W.te=function(a){var b=a.getAttributeNode("tabindex");if(b&&b.specified){a=a.tabIndex;return typeof a=="number"&&a>=0}return k};W.ve=function(a,b){if(b)a.tabIndex=0;else a.removeAttribute("tabIndex")};
W.pa=function(a){if(V&&"innerText"in a)a=a.innerText[A](/(\r\n|\r|\n)/g,"\n");else{var b=[];W.Gb(a,b,i);a=b[N]("")}a=a[A](/\xAD/g,"");a=a[A](/ +/g," ");if(a!=" ")a=a[A](/^\s*/,"");return a};W.se=function(a){var b=[];W.Gb(a,b,k);return b[N]("")};W.Gb=function(a,b,c){if(!(a[eb]in W.ac))if(a[B]==3)c?b[s](ha(a[Nb])[A](/(\r\n|\r|\n)/g,"")):b[s](a[Nb]);else if(a[eb]in W.eb)b[s](W.eb[a[eb]]);else for(a=a[I];a;){W.Gb(a,b,c);a=a[Jb]}};W.xc=function(a){return W.pa(a)[x]};
W.yc=function(a,b){b=b||W.Q(a)[E];for(var c=[];a&&a!=b;){for(var d=a;d=d[Ea];)c[Mb](W.pa(d));a=a[L]}return Qc(c[N](""))[A](/ +/g," ")[x]};W.pe=function(a,b,c){a=[a];for(var d=0,e;a[x]>0&&d<b;){e=a.pop();if(!(e[eb]in W.ac))if(e[B]==3){var f=e[Nb][A](/(\r\n|\r|\n)/g,"")[A](/ +/g," ");d+=f[x]}else if(e[eb]in W.eb)d+=W.eb[e[eb]][x];else for(f=e[Gb][x]-1;f>=0;f--)a[s](e[Gb][f])}if(Xb(c)){c.ue=e?e[Nb][x]+b-d-1:0;c.M=e}return e};
W.Dd=function(a){if(a&&typeof a[x]=="number")if(Xb(a))return typeof a[Za]=="function"||typeof a[Za]=="string";else if(Wb(a))return typeof a[Za]=="function";return k};W.mc=function(a,b,c){var d=b?b.toUpperCase():j;return W.Db(a,function(e){return(!d||e[eb]==d)&&(!c||W.n.ra(e,c))},i)};W.Db=function(a,b,c,d){if(!c)a=a[L];c=d==j;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a[L];e++}return j};function Od(a){this.a=a||Q[Ta]||ia}P=Od[y];P.P=W.P;P.o=Pb("a");
P.l=function(a){return S(a)?this.a.getElementById(a):a};P.Xb=Od[y].l;P.Va=function(a,b,c){return W.qc(this.a,a,b,c)};P.Pc=Od[y].Va;P.pb=W.pb;P.Hb=function(a){return W.Hb(a||this.Xa())};P.ld=function(){return W.nc(this.Xa())};P.z=function(){return W.fc(this.a,arguments)};P.Qc=Od[y].z;P.createElement=function(a){return this.a[H](a)};P.createTextNode=function(a){return this.a[Wa](a)};P.$c=function(a,b,c){return W.gc(this.a,a,b,!!c)};P.Cd=function(a){return W.Gc(this.a,a)};
P.kd=function(){return this.Ca()?"CSS1Compat":"BackCompat"};P.Ca=function(){return W.Da(this.a)};P.Xa=function(){return W.Ib(this.a)};P.oc=function(){return W.Eb(this.a)};P.xa=function(){return W.pc(this.a)};P.appendChild=W[p];P.Ia=W.Ia;P.Ob=W.Ob;P.Nb=W.Nb;P.removeNode=W[Bb];P.replaceNode=W.replaceNode;P.Cb=W.Cb;P.rc=W.rc;P.uc=W.uc;P.vc=W.vc;P.zc=W.zc;P.wc=W.wc;P.Ac=W.Ac;P.Pb=W.Pb;za(P,W[Eb]);P.Q=W.Q;P.Z=W.Z;P.Wa=W.Wa;P.na=W.na;P.kc=W.kc;P.lc=W.lc;P.pa=W.pa;P.xc=W.xc;P.yc=W.yc;P.mc=W.mc;P.Db=W.Db;function Pd(a,b){this.type=a;ua(this,b);ra(this,this[jb])}U(Pd,uc);Pd[y].D=function(){delete this[Db];delete this[jb];delete this[fb]};Pd[y].a=k;Pd[y].b=i;function Qd(a,b){a&&Rd(this,a,b)}U(Qd,Pd);P=Qd[y];ua(P,j);P.relatedTarget=j;P.offsetX=0;P.offsetY=0;P.clientX=0;P.clientY=0;P.screenX=0;P.screenY=0;P.button=0;P.keyCode=0;P.charCode=0;P.ctrlKey=k;P.altKey=k;P.shiftKey=k;P.metaKey=k;P.Nd=k;P.jc=j;
function Rd(a,b,c){var d=a.type=b[Db];ua(a,b[jb]||b.srcElement);ra(a,c);if(c=b.relatedTarget){if(sd)try{c=c[eb]&&c}catch(e){c=j}}else if(d=="mouseover")c=b.fromElement;else if(d=="mouseout")c=b.toElement;a.relatedTarget=c;a.offsetX=b.offsetX!==ca?b.offsetX:b.layerX;a.offsetY=b.offsetY!==ca?b.offsetY:b.layerY;a.clientX=b.clientX!==ca?b.clientX:b.pageX;a.clientY=b.clientY!==ca?b.clientY:b.pageY;a.screenX=b[kb]||0;a.screenY=b[lb]||0;a.button=b.button;a.keyCode=b[qb]||0;a.charCode=b.charCode||(d=="keypress"?
b[qb]:0);a.ctrlKey=b.ctrlKey;a.altKey=b.altKey;a.shiftKey=b.shiftKey;a.metaKey=b.metaKey;a.Nd=yd?b.metaKey:b.ctrlKey;a.jc=b;delete a.b;delete a.a}V&&Hd("8");Qd[y].D=function(){Qd.A.D[G](this);this.jc=j;ua(this,j);ra(this,j);this.relatedTarget=j};function Sd(a,b){this.d=b;this.b=[];a=a;if(a>this.d)g(aa("[goog.structs.SimplePool] Initial cannot be greater than max"));for(b=0;b<a;b++)this.b[s](this.a?this.a():{})}U(Sd,uc);Sd[y].a=j;Sd[y].c=j;function Td(a){if(a.b[x])return a.b.pop();return a.a?a.a():{}}function Ud(a,b){a.b[x]<a.d?a.b[s](b):Vd(a,b)}function Vd(a,b){if(a.c)a.c(b);else if(Wb(b.t))b.t();else for(var c in b)delete b[c]}Sd[y].D=function(){Sd.A.D[G](this);for(var a=this.b;a[x];)Vd(this,a.pop());delete this.b};var Wd,Xd,Yd="ScriptEngine"in Q;Xd=(Wd=Yd&&Q.ScriptEngine()=="JScript")?Q.ScriptEngineMajorVersion()+"."+Q.ScriptEngineMinorVersion()+"."+Q.ScriptEngineBuildVersion():"0";var Zd=Wd,$d=Xd;function ae(){}var be=0;ae[y].da=0;ae[y].Ja=k;ae[y].a=k;ae[y].handleEvent=function(a){if(this.b)return this.Fa[G](this.mb||this.src,a);return this.Fa[Ab][G](this.Fa,a)};var ce,de,ee,fe,ge,he,ie,je,ke,le,me;
(function(){function a(){return{p:0,$:0}}function b(){return[]}function c(){function u(sa){return h[G](u.src,u.da,sa)}return u}function d(){return new ae}function e(){return new Qd}var f=Zd&&!(cd($d,"5.7")>=0),h;he=function(u){h=u};if(f){ce=function(){return Td(n)};de=function(u){Ud(n,u)};ee=function(){return Td(q)};fe=function(u){Ud(q,u)};ge=function(){return Td(r)};ie=function(){Ud(r,c())};je=function(){return Td(t)};ke=function(u){Ud(t,u)};le=function(){return Td(w)};me=function(u){Ud(w,u)};var n=
new Sd(0,600);n.a=a;var q=new Sd(0,600);q.a=b;var r=new Sd(0,600);r.a=c;var t=new Sd(0,600);t.a=d;var w=new Sd(0,600);w.a=e}else{ce=a;de=Sb;ee=b;fe=Sb;ge=c;ie=Sb;je=d;ke=Sb;le=e;me=Sb}})();var ne={},oe={},pe={},qe="on",re={};
function se(a,b,c,d,e){if(b)if(R(b)){for(var f=0;f<b[x];f++)se(a,b[f],c,d,e);return j}else{d=!!d;var h=oe;b in h||(h[b]=ce());h=h[b];if(!(d in h)){h[d]=ce();h.p++}h=h[d];var n=Yb(a),q;h.$++;if(h[n]){q=h[n];for(f=0;f<q[x];f++){h=q[f];if(h.Fa==c&&h.mb==e){if(h.Ja)break;return q[f].da}}}else{q=h[n]=ee();h.p++}f=ge();f.src=a;var r=h=je();c=c;var t=f,w=a,u=b,sa=d;e=e;if(Wb(c))r.b=i;else if(c&&c[Ab]&&Wb(c[Ab]))r.b=k;else g(aa("Invalid listener argument"));r.Fa=c;r.c=t;r.src=w;r.type=u;r.Oa=!!sa;r.mb=e;
r.a=k;r.da=++be;r.Ja=k;e=h.da;f.da=e;q[s](h);ne[e]=h;pe[n]||(pe[n]=ee());pe[n][s](h);if(a.addEventListener){if(a==Q||!a.hc)a.addEventListener(b,f,d)}else a.attachEvent(te(b),f);return e}else g(aa("Invalid event type"))}function ue(a,b,c,d,e){if(R(b)){for(var f=0;f<b[x];f++)ue(a,b[f],c,d,e);return j}d=!!d;a=ve(a,b,d);if(!a)return k;for(f=0;f<a[x];f++)if(a[f].Fa==c&&a[f].Oa==d&&a[f].mb==e)return we(a[f].da);return k}
function we(a){if(!ne[a])return k;var b=ne[a];if(b.Ja)return k;var c=b.src,d=b[Db],e=b.c,f=b.Oa;if(c.removeEventListener){if(c==Q||!c.hc)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(te(d),e);c=Yb(c);e=oe[d][f][c];if(pe[c]){var h=pe[c];zc(h,b);h[x]==0&&delete pe[c]}b.Ja=i;e.Jc=i;xe(d,f,c,e);delete ne[a];return i}
function xe(a,b,c,d){if(!d.nb)if(d.Jc){for(var e=0,f=0;e<d[x];e++)if(d[e].Ja){var h=d[e].c;h.src=j;ie(h);ke(d[e])}else{if(e!=f)d[f]=d[e];f++}la(d,f);d.Jc=k;if(f==0){fe(d);delete oe[a][b][c];oe[a][b].p--;if(oe[a][b].p==0){de(oe[a][b]);delete oe[a][b];oe[a].p--}if(oe[a].p==0){de(oe[a]);delete oe[a]}}}}
function ye(a,b,c){var d=0,e=a==j,f=b==j,h=c==j;c=!!c;if(e)Ic(pe,function(q){for(var r=q[x]-1;r>=0;r--){var t=q[r];if((f||b==t[Db])&&(h||c==t.Oa)){we(t.da);d++}}});else{a=Yb(a);if(pe[a]){a=pe[a];for(e=a[x]-1;e>=0;e--){var n=a[e];if((f||b==n[Db])&&(h||c==n.Oa)){we(n.da);d++}}}}return d}function ve(a,b,c){var d=oe;if(b in d){d=d[b];if(c in d){d=d[c];a=Yb(a);if(d[a])return d[a]}}return j}function te(a){if(a in re)return re[a];return re[a]=qe+a}
function ze(a,b,c,d,e){var f=1;b=Yb(b);if(a[b]){a.$--;a=a[b];if(a.nb)a.nb++;else a.nb=1;try{for(var h=a[x],n=0;n<h;n++){var q=a[n];if(q&&!q.Ja)f&=Ae(q,e)!==k}}finally{a.nb--;xe(c,d,b,a)}}return ba(f)}function Ae(a,b){b=a[Ab](b);a.a&&we(a.da);return b}
function Be(a,b){if(!ne[a])return i;a=ne[a];var c=a[Db],d=oe;if(!(c in d))return i;d=d[c];var e,f;if(V){e=b||Rb("window.event");b=i in d;var h=k in d;if(b){if(e[qb]<0||e.returnValue!=ca)return i;a:{var n=e,q=k;if(n[qb]==0)try{n.keyCode=-1;break a}catch(r){q=i}if(q||n.returnValue==ca)n.returnValue=i}}n=le();Rd(n,e,this);e=i;try{if(b){for(var t=ee(),w=n[fb];w;w=w[L])t[s](w);f=d[i];f.$=f.p;for(var u=t[x]-1;!n.a&&u>=0&&f.$;u--){ra(n,t[u]);e&=ze(f,t[u],c,i,n)}if(h){f=d[k];f.$=f.p;for(u=0;!n.a&&u<t[x]&&
f.$;u++){ra(n,t[u]);e&=ze(f,t[u],c,k,n)}}}else e=Ae(a,n)}finally{if(t){la(t,0);fe(t)}n.t();me(n)}return e}f=new Qd(b,this);try{e=Ae(a,f)}finally{f.t()}return e}he(Be);function Ce(a,b,c,d){this.top=a;Ca(this,b);xa(this,c);ta(this,d)}Ce[y].L=function(){return new Ce(this.top,this[O],this[J],this[F])};ka(Ce[y],function(){return"("+this.top+"t, "+this[O]+"r, "+this[J]+"b, "+this[F]+"l)"});za(Ce[y],function(a){a=!this||!a?k:a instanceof Ce?a[F]>=this[F]&&a[O]<=this[O]&&a.top>=this.top&&a[J]<=this[J]:a.x>=this[F]&&a.x<=this[O]&&a.y>=this.top&&a.y<=this[J];return a});function De(a,b,c,d){ta(this,a);this.top=b;na(this,c);Ba(this,d)}De[y].L=function(){return new De(this[F],this.top,this[z],this[M])};ka(De[y],function(){return"("+this[F]+", "+this.top+" - "+this[z]+"w x "+this[M]+"h)"});function Ee(a,b){var c=o.max(a[F],b[F]),d=o.min(a[F]+a[z],b[F]+b[z]);if(c<=d){var e=o.max(a.top,b.top);b=o.min(a.top+a[M],b.top+b[M]);if(e<=b){ta(a,c);a.top=e;na(a,d-c);Ba(a,b-e);return i}}return k}
za(De[y],function(a){return a instanceof De?this[F]<=a[F]&&this[F]+this[z]>=a[F]+a[z]&&this.top<=a.top&&this.top+this[M]>=a.top+a[M]:a.x>=this[F]&&a.x<=this[F]+this[z]&&a.y>=this.top&&a.y<=this.top+this[M]});function Fe(a,b,c){S(b)?Ge(a,c,b):Ic(b,bc(Ge,a))}function Ge(a,b,c){a[D][He(c)]=b}function Ie(a,b){var c=W.Q(a);if(c[Ib]&&c[Ib].getComputedStyle)if(a=c[Ib].getComputedStyle(a,""))return a[b];return j}function Je(a,b){return Ie(a,b)||(a[wb]?a[wb][b]:j)||a[D][b]}function Ke(a,b,c){var d,e=sd&&(yd||zd)&&Hd("1.9");if(b instanceof Fc){d=b.x;b=b.y}else{d=b;b=c}ta(a[D],typeof d=="number"?(e?o[Qa](d):d)+"px":d);a[D].top=typeof b=="number"?(e?o[Qa](b):b)+"px":b}
function Le(a){var b=a[Ga]();if(V){a=a[hb];b.left-=a[Ob][vb]+a[E][vb];b.top-=a[Ob][zb]+a[E][zb]}return b}function Me(a){if(V)return a.offsetParent;var b=W.Q(a),c=Je(a,"position"),d=c=="fixed"||c=="absolute";for(a=a[L];a&&a!=b;a=a[L]){c=Je(a,"position");d=d&&c=="static"&&a!=b[Ob]&&a!=b[E];if(!d&&(a.scrollWidth>a[Oa]||a[pb]>a[tb]||c=="fixed"||c=="absolute"))return a}return j}
function Ne(a){var b=new Ce(0,Infinity,Infinity,0),c=W.P(a),d=c.o()[E],e=c.oc(),f;for(a=a;a=Me(a);)if((!V||a[Oa]!=0)&&(!td||a[tb]!=0||a!=d)&&(a.scrollWidth!=a[Oa]||a[pb]!=a[tb])&&Je(a,"overflow")!="visible"){var h=Oe(a),n;n=a;if(sd&&!Hd("1.9")){var q=fa(Ie(n,"borderLeftWidth"));if(Pe(n)){var r=n[Va]-n[Oa]-q-fa(Ie(n,"borderRightWidth"));q+=r}n=new Fc(q,fa(Ie(n,"borderTopWidth")))}else n=new Fc(n[vb],n[zb]);h.x+=n.x;h.y+=n.y;b.top=o.max(b.top,h.y);Ca(b,o.min(b[O],h.x+a[Oa]));xa(b,o.min(b[J],h.y+a[tb]));
ta(b,o.max(b[F],h.x));f=f||a!=e}d=e[ub];e=e[Da];if(td){b.left+=d;b.top+=e}else{ta(b,o.max(b[F],d));b.top=o.max(b.top,e)}if(!f||td){b.right+=d;b.bottom+=e}c=c.Hb();Ca(b,o.min(b[O],d+c[z]));xa(b,o.min(b[J],e+c[M]));return b.top>=0&&b[F]>=0&&b[J]>b.top&&b[O]>b[F]?b:j}
function Oe(a){var b,c=W.Q(a),d=Je(a,"position"),e=sd&&c[nb]&&!a[Ga]&&d=="absolute"&&(b=c[nb](a))&&(b[kb]<0||b[lb]<0),f=new Fc(0,0),h;b=c?c[B]==9?c:W.Q(c):W.o();h=V&&!W.P(b).Ca()?b[E]:b[Ob];if(a==h)return f;if(a[Ga]){b=Le(a);a=W.P(c).xa();f.x=b[F]+a.x;f.y=b.top+a.y}else if(c[nb]&&!e){b=c[nb](a);a=c[nb](h);f.x=b[kb]-a[kb];f.y=b[lb]-a[lb]}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b[vb]||0;f.y+=b[zb]||0}if(td&&Je(b,"position")=="fixed"){f.x+=c[E][ub];f.y+=c[E][Da];break}b=b.offsetParent}while(b&&
b!=a);if(rd||td&&d=="absolute")f.y-=c[E].offsetTop;for(b=a;(b=Me(b))&&b!=c[E]&&b!=h;){f.x-=b[ub];if(!rd||b[K]!="TR")f.y-=b[Da]}}return f}function Qe(a,b){var c=new Fc(0,0),d=W.Xa(W.Q(a));a=a;do{var e=d==b?Oe(a):Re(a);c.x+=e.x;c.y+=e.y}while(d&&d!=b&&(a=d.frameElement)&&(d=d.parent));return c}function Re(a){var b=new Fc;if(a[B]==1)if(a[Ga]){var c=Le(a);b.x=c[F];b.y=c.top}else{c=W.P(a).xa();a=Oe(a);b.x=a.x-c.x;b.y=a.y-c.y}else{b.x=a.clientX;b.y=a.clientY}return b}
function Se(a,b,c){if(b instanceof Hc){c=b[M];b=b[z]}else{if(c==ca)g(aa("missing height argument"));c=c}na(a[D],typeof b=="number"?o[Qa](b)+"px":b);Ba(a[D],typeof c=="number"?o[Qa](c)+"px":c)}
function Te(a){var b=rd&&!Hd("10");if(Je(a,"display")!="none")return b?new Hc(a[Va]||a[Oa],a[Lb]||a[tb]):new Hc(a[Va],a[Lb]);var c=a[D],d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";Aa(c,"inline");if(b){b=a[Va]||a[Oa];a=a[Lb]||a[tb]}else{b=a[Va];a=a[Lb]}Aa(c,d);c.position=f;c.visibility=e;return new Hc(b,a)}function Ue(a){var b=Oe(a);a=Te(a);return new De(b.x,b.y,a[z],a[M])}var Ve={};
function He(a){return Ve[a]||(Ve[a]=ha(a)[A](/\-([a-z])/g,function(b,c){return c.toUpperCase()}))}function X(a,b){Aa(a[D],b?"":"none")}function We(a,b){if(V)a.cssText=b;else{var c=td?"innerText":"innerHTML";a[c]=b}}function Pe(a){return"rtl"==Je(a,"direction")}function Xe(a){return new Hc(a[Va],a[Lb])}
function Ye(a,b){var c=W.Q(a),d=W.P(c).Ca();if(V&&(!d||!Hd("8"))){c=a[D];if(d){c.pixelWidth=b[z];c.pixelHeight=b[M]}else{var e=a,f="padding";if(V){d=Ze(e,f+"Left");var h=Ze(e,f+"Right"),n=Ze(e,f+"Top");e=Ze(e,f+"Bottom");d=new Ce(n,h,e,d)}else{d=Ie(e,f+"Left");h=Ie(e,f+"Right");n=Ie(e,f+"Top");e=Ie(e,f+"Bottom");d=new Ce(fa(n),fa(h),fa(e),fa(d))}e=a;if(V){a=$e(e,"borderLeft");h=$e(e,"borderRight");n=$e(e,"borderTop");e=$e(e,"borderBottom");a=new Ce(n,h,e,a)}else{a=Ie(e,"borderLeftWidth");h=Ie(e,"borderRightWidth");
n=Ie(e,"borderTopWidth");e=Ie(e,"borderBottomWidth");a=new Ce(fa(n),fa(h),fa(e),fa(a))}c.pixelWidth=b[z]+a[F]+d[F]+d[O]+a[O];c.pixelHeight=b[M]+a.top+d.top+d[J]+a[J]}}else{b=b;c="content-box";a=a[D];if(sd)a.MozBoxSizing=c;else if(td)a.WebkitBoxSizing=c;else if(rd&&!Hd("9.50"))c?a.setProperty("box-sizing",c):a.removeProperty("box-sizing");else a.le=c;na(a,b[z]+"px");Ba(a,b[M]+"px")}}
function af(a,b,c,d){if(/^\d+px?$/[Ha](b))return ea(b,10);else{var e=a[D][c],f=a.runtimeStyle[c];a.runtimeStyle[c]=a[wb][c];a[D][c]=b;b=a[D][d];a[D][c]=e;a.runtimeStyle[c]=f;return b}}function Ze(a,b){return af(a,a[wb]?a[wb][b]:j,"left","pixelLeft")}var bf={thin:2,medium:4,thick:6};function $e(a,b){if((a[wb]?a[wb][b+"Style"]:j)=="none")return 0;b=a[wb]?a[wb][b+"Width"]:j;if(b in bf)return bf[b];return af(a,b,"left","pixelLeft")};function cf(a){this.c=a}U(cf,uc);var df=new Sd(0,100);function Y(a,b,c,d,e,f){if(R(c))for(var h=0;h<c[x];h++)Y(a,b,c[h],d,e,f);else{c=se(b,c,d||a,e||k,f||a.c||a);b=a;c=c;if(b.a)b.a[c]=i;else if(b.b){b.a=Td(df);b.a[b.b]=i;b.b=j;b.a[c]=i}else b.b=c}return a}
function ef(a,b,c,d,e,f){if(a.b||a.a)if(R(c))for(var h=0;h<c[x];h++)ef(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.c||a;e=!!(e||k);if(b=ve(b,c,e))for(c=0;c<b[x];c++)if(b[c].Fa==d&&b[c].Oa==e&&b[c].mb==f){b=b[c];break a}b=j}if(b){b=b.da;we(b);if(a.a)Lc(a.a,b);else if(a.b==b)a.b=j}}return a}function ff(a){if(a.a){for(var b in a.a){we(b);delete a.a[b]}Ud(df,a.a);a.a=j}else a.b&&we(a.b)}cf[y].D=function(){cf.A.D[G](this);ff(this)};cf[y].handleEvent=function(){g(aa("EventHandler.handleEvent not implemented"))};function gf(){}U(gf,uc);P=gf[y];P.hc=i;P.ob=j;P.Tb=function(a){this.ob=a};P.addEventListener=function(a,b,c,d){se(this,a,b,c,d)};P.removeEventListener=function(a,b,c,d){ue(this,a,b,c,d)};
P.dispatchEvent=function(a){a=a;if(S(a))a=new Pd(a,this);else if(a instanceof Pd)ua(a,a[jb]||this);else{var b=a;a=new Pd(a[Db],this);Oc(a,b)}b=1;var c,d=a[Db],e=oe;if(d in e){e=e[d];d=i in e;var f;if(d){c=[];for(f=this;f;f=f.ob)c[s](f);f=e[i];f.$=f.p;for(var h=c[x]-1;!a.a&&h>=0&&f.$;h--){ra(a,c[h]);b&=ze(f,c[h],a[Db],i,a)&&a.b!=k}}if(f=k in e){f=e[k];f.$=f.p;if(d)for(h=0;!a.a&&h<c[x]&&f.$;h++){ra(a,c[h]);b&=ze(f,c[h],a[Db],k,a)&&a.b!=k}else for(c=this;!a.a&&c&&f.$;c=c.ob){ra(a,c);b&=ze(f,c,a[Db],
k,a)&&a.b!=k}}a=ba(b)}else a=i;return a};P.D=function(){gf.A.D[G](this);ye(this);this.ob=j};function hf(){}Tb(hf);hf[y].a=0;hf.sc();function Z(a){this.m=a||W.P();this.Ud=jf}U(Z,gf);Z[y].G=hf.sc();var jf=j;P=Z[y];P.R=j;P.m=j;P.sa=k;P.f=j;P.Ud=j;P.Kd=j;P.Ga=j;P.V=j;P.gb=j;P.ee=k;P.l=Pb("f");P.Tb=function(a){if(this.Ga&&this.Ga!=a)g(aa("Method not supported"));Z.A.Tb[G](this,a)};P.P=Pb("m");P.z=function(){this.f=this.m[H]("div")};P.la=function(a){kf(this,a)};function kf(a,b,c){if(a.sa)g(aa("Component already rendered"));a.f||a.z();b?b[$a](a.f,c||j):a.m.o()[E][p](a.f);if(!a.Ga||a.Ga.sa)a.W()}
Z[y].W=function(){this.sa=i;this.V&&xc(this.V,function(a){!a.sa&&a.l()&&a.W()},void 0)};Z[y].J=function(){this.V&&xc(this.V,function(a){a.sa&&a.J()},void 0);this.r&&ff(this.r);this.sa=k};Z[y].D=function(){Z.A.D[G](this);this.sa&&this.J();if(this.r){this.r.t();delete this.r}this.V&&xc(this.V,function(a){a.t()},void 0);!this.ee&&this.f&&W[Bb](this.f);this.Ga=this.Kd=this.f=this.gb=this.V=j};function $(a,b){return(a.R||(a.R=":"+(a.G.a++)[v](36)))+"."+b}
Z[y].removeChild=function(a,b){if(a){var c=S(a)?a:a.R||(a.R=":"+(a.G.a++)[v](36));a=this.gb&&c?Mc(this.gb,c)||j:j;if(c&&a){Lc(this.gb,c);zc(this.V,a);if(b){a.J();a.f&&W[Bb](a.f)}b=a;if(b==j)g(aa("Unable to set parent component"));b.Ga=j;Z.A.Tb[G](b,j)}}if(!a)g(aa("Child is not in parent component"));return a};Z[y].Ia=function(a){for(;this.V&&this.V[x]!=0;)this[ib](this.V?this.V[0]||j:j,a)};function lf(a,b,c,d,e,f,h,n){var q,r=c.offsetParent;if(r){var t=r[K]=="HTML"||r[K]=="BODY";if(!t||Je(r,"position")!="static"){q=Oe(r);t||(q=Gc(q,new Fc(r[ub],r[Da])))}}t=a;r=Ue(t);(t=Ne(t))&&Ee(r,new De(t[F],t.top,t[O]-t[F],t[J]-t.top));t=r=r;var w=W.P(a),u=W.P(c);if(w.o()!=u.o()){var sa=w.o()[E];u=Qe(sa,u.Xa());u=Gc(u,Oe(sa));if(V&&!w.Ca())u=Gc(u,w.xa());t.left+=u.x;t.top+=u.y}a=(b&4&&Pe(a)?b^2:b)&-5;b=new Fc(a&2?r[F]+r[z]:r[F],a&1?r.top+r[M]:r.top);if(q)b=Gc(b,q);if(e){b.x+=(a&2?-1:1)*e.x;b.y+=
(a&1?-1:1)*e.y}var ga;if(h)if((ga=Ne(c))&&q){ga.top=o.max(0,ga.top-q.y);ga.right-=q.x;ga.bottom-=q.y;ta(ga,o.max(0,ga[F]-q.x))}a:{e=b;c=c;d=d;f=f;ga=ga;h=h;q=n;e=e.L();n=0;d=(d&4&&Pe(c)?d^2:d)&-5;a=Te(c);q=q?q.L():a;if(f||d!=0){if(d&2)e.x-=q[z]+(f?f[O]:0);else if(f)e.x+=f[F];if(d&1)e.y-=q[M]+(f?f[J]:0);else if(f)e.y+=f.top}if(h){n=ga?mf(e,q,ga,h):256;if(n&496){n=n;break a}}Ke(c,e);h=a==q?i:!a||!q?k:a[z]==q[z]&&a[M]==q[M];h||Se(c,q);n=n}return n}
function mf(a,b,c,d){var e=0;if(a.x<c[F]&&d&1){a.x=c[F];e|=1}if(a.x<c[F]&&a.x+b[z]>c[O]&&d&16){b.width-=a.x+b[z]-c[O];e|=4}if(a.x+b[z]>c[O]&&d&1){a.x=o.max(c[O]-b[z],c[F]);e|=1}if(d&2)e|=(a.x<c[F]?16:0)|(a.x+b[z]>c[O]?32:0);if(a.y<c.top&&d&4){a.y=c.top;e|=2}if(a.y>=c.top&&a.y+b[M]>c[J]&&d&32){b.height-=a.y+b[M]-c[J];e|=8}if(a.y+b[M]>c[J]&&d&4){a.y=o.max(c[J]-b[M],c.top);e|=2}if(d&8)e|=(a.y<c.top?64:0)|(a.y+b[M]>c[J]?128:0);return e};var nf=new RegExp("^(ar|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)");function of(a){this.a=Zd?[]:"";a!=j&&this.F[Fb](this,arguments)}of[y].ea=function(a){this.clear();this.F(a)};if(Zd){of[y].b=0;of[y].F=function(a,b){if(b==j)this.a[this.b++]=a;else{this.a[s][Fb](this.a,arguments);this.b=this.a[x]}return this}}else of[y].F=function(a,b){this.a+=a;if(b!=j)for(var c=1;c<arguments[x];c++)this.a+=arguments[c];return this};of[y].clear=function(){if(Zd){la(this.a,0);this.b=0}else this.a=""};ka(of[y],function(){if(Zd){var a=this.a[N]("");this.clear();a&&this.F(a);return a}else return this.a});var pf=of;function qf(a,b){var c=b||new pf;c.F('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.C,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="',a.id,'" class="goog-te-menu"></div></body>');if(!b)return c[v]()}
function rf(a,b){var c=b||new pf;c.F('<iframe id="',a.id,'" class="goog-te-banner-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');if(!b)return c[v]()}
function sf(a,b){var c=b||new pf;c.F('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.C,'"></head><body class="goog-te-banner" scroll="no" border=0 dir="',a.dir,'"><table border=0 cellspacing=0 cellpadding=0 width=100% height=100%><tr valign=middle><td width=1 nowrap><a href="',a.Qb,'" class="goog-logo-link" target="_blank"><img src="',a.ta,'" alt="Google ',"Traductor de Google",'"></a></td><td><table border=0 cellspacing=0 cellpadding=0 width=100% height=100%><tr id="',
a.Sd,'" style="display:none" valign=middle><td><span class="goog-te-banner-content">',a.Rd," ");tf(a,c);c.F("</span>",a.va?'<div><span class="goog-te-banner-info" title="'+a.va+'">'+a.va+"</span></div>":"",'</td><td width=1 nowrap><button id="',a.Zc,'"><b>',"Traducir",'</b></button></td><td width=1 nowrap><button id="',a.Ld,'"></button></td></tr><tr id="',a.Qd,'" style="display:none" valign=middle><td><span class="goog-te-banner-content">',"Traducci\u00f3n en curso",'&nbsp;<span dir="ltr">(<b id="',
a.Pd,'"></b>%)</span>&nbsp;<img src="',a.Hd,'"> ');tf(a,c);c.F('</span></td><td width=1 nowrap><button id="',a.Wc,'">',"Cancelar",'</button></td></tr><tr id="',a.jd,'" style="display:none"><td><span class="goog-te-banner-content">',a.hd," ");tf(a,c);c.F('</span></td><td width=1 nowrap><button id="',a.Td,'">',"Mostrar texto original",'</button></td></tr><tr id="',a.gd,'" style="display:none" valign=middle><td><span id="',a.fd,'" class="goog-te-banner-content"></span></td></tr></table></td><td width=1 nowrap><a id="',
a.Yc,'" class="goog-close-link" href="javascript:void(0)" title="',"Cerrar",'"><img src="',a.hb,'" width="15" height="15" style="background-image:url(',a.Lb,');background-position:-28px 0px"></a></td></tr></table></body>');if(!b)return c[v]()}function tf(a,b){var c=b||new pf;c.F('<a href="',a.Gd,'" style="margin-left:20px;margin-right:20px" target="_blank">',"M\u00e1s informaci\u00f3n","</a>");if(!b)return c[v]()}
function uf(a,b){var c=b||new pf;c.F('<span id="',a.id,'"></span>');if(!b)return c[v]()}function vf(a,b){var c=b||new pf;c.F('<div id="',a.id,'"></div>',a.Od);if(!b)return c[v]()}function wf(a,b){var c=b||new pf;c.F('<iframe id="',a.id,'" frameBorder=0 src="javascript:\'\'" class="goog-te-ftab-frame skiptranslate" style="visibility:visible"></iframe>');if(!b)return c[v]()}
function xf(a,b){var c=b||new pf;c.F('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.C,'"></head><body class="goog-te-ftab ',a.jb,'" scroll="no" style="overflow:hidden" dir="',a.dir,'"><a id="',a.de,'" href="javascript:void(0)" class="goog-te-ftab-link" style="position:absolute;left:0px;top:0px"><span>',"Traducir","</span></a></body>");if(!b)return c[v]()}
function yf(a,b){var c=b||new pf;c.F('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="',a.id,'" width="400" height="500" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab"><param name="movie" value="',a.src,'"/><param name="allowScriptAccess" value="always"/><embed src="',a.src,'" width="400" height="500" name="',a.id,'" play="true" loop="false" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed></object>');
if(!b)return c[v]()}function zf(a,b){var c=b||new pf;c.F('<iframe id="',a.id,'" class="goog-te-balloon-frame skiptranslate" frameBorder=0 src="javascript:\'\'" style="visibility:visible"></iframe>');if(!b)return c[v]()}
function Af(a,b){var c=b||new pf;c.F('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF8"><link rel="stylesheet" type="text/css" href="',a.C,'"></head><body scroll="no" style="margin:0px;overflow:hidden" dir="',a.dir,'" marginHeight=0 marginWidth=0 leftMargin=0 topMargin=0 border=0><div id="content" class="goog-te-balloon"><table border=0 cellspacing=0 cellpadding=0 width=100%><tr valign=middle><td nowrap><b>',"Original text:",'</b></td><td id="logo" width=1 nowrap>',a.Kb?"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+
a.ta+"',sizingMethod='scale');\"></span>":'<img src="'+a.ta+'">','</td><td width=8></td><td width=1 nowrap><a id="close" href="javascript:void(0)" title="',"Cerrar",'"><img src="',a.hb,'" width="15" height="15" style="background-image:url(',a.Lb,');background-position:-28px 0px"></a></td></tr></table><div id="original" class="goog-te-balloon-text"></div><div id="zippy" class="goog-te-balloon-zippy" style="display:none"><img id="zippy_img" class="plus" width="12" height="12" src="',a.hb,'"><span>',
"Contribute a better translation",'</span></div><div id="feedback" style="display:none"><iframe name="feedback-frame" frameBorder=0 style="width:100%;display:none"></iframe></div><div class="goog-te-balloon-form" style="display:none"><form id="suggestForm" target="feedback-frame" method="post"><input type="hidden" name="gtrans"><input type="hidden" name="text"><input type="hidden" name="langpair"><input type="hidden" name="u"><input type="hidden" name="client"><input type="hidden" name="oe" value="UTF-8"><textarea rows="3" name="utrans"></textarea><div style="text-align:',
a.dir=="rtl"?"left":"right",'"><input type="submit" value="',"Contribute",'"></div></form></div><div id="forward" class="goog-te-balloon-footer" style="display:none"><a id="forward_link" href="javascript:void(0)">',"Contribute a better translation","</a></div></div></body>");if(!b)return c[v]()};function Bf(a){for(var b={},c=0;c<a[x];++c)b[a[c]]=i;return b}function Cf(a,b){this.c=[];this.d=a||0;this.g=b||1;this.b=0;this.a=i}Cf[y].add=function(a){this.c[s](a)};Cf[y].go=function(){if(this.a){this.a=k;l[Sa](T(this.e,this),this.d)}};oa(Cf[y],function(){this.a=i});Cf[y].e=function(){if(!this.a){for(var a=0;a<this.g;++a)if(this.c[this.b]){this.c[this.b][G]();this.b++}else{this.a=i;return}l[Sa](T(this.e,this),this.d)}};function Df(a){this.Pa=a?[a]:[];this.ua=[0];this.ib=k}
function Ef(a,b){if(a.ib)return b;a.ua[s](0);var c=a.ua[x]-1;return T(function(){this.ua[c]++;b&&b[Fb](j,arguments);Ff(this)},a)}function Gf(a,b){if(a.ib)return b;return T(function(){if(this.ib)b[Fb](j,arguments);else{var c=arguments;this.Pa[s](function(){b[Fb](j,c)})}},a)}Df[y].Sa=function(){this.ua[0]=1;Ff(this)};function Ff(a){for(var b=0;b<a.ua[x];++b)if(a.ua[b]==0)return;for(b=0;b<a.Pa[x];++b){var c=a.Pa[b];a.Pa[b]=j;c[G]()}a.Pa=[];a.ua=[];a.ib=i}function Hf(a){this.Nc=a;this.ka=this.sb=k}
function If(a,b){return T(function(){b&&b[Fb](j,arguments);if(this.ka){if(!this.sb){this.Nc[G]();this.sb=i}}else this.sb=i},a)}Hf[y].Sa=function(){if(!this.ka){this.ka=i;this.sb&&this.Nc[G]()}};function Jf(a,b,c,d){this.c=b;this.g=a;this.d=c||0;this.p=d||0;this.b=this.ka=k}Jf[y].go=function(){if(!this.ka)this.a=l[Sa](T(this.e,this),this.d)};Jf[y].e=function(){if(this.ka=(this.b=!!this.g[G]())||--this.p<=0){this.c[G](j,this.b);this.a=0}else this.a=l[Sa](T(this.e,this),this.d)};
oa(Jf[y],function(){this.a&&l[La](this.a);this.ka=i;this.c[G](j,this.b)});function Kf(a){var b="";if(a)if(a[B]==3)b=ha(a[Nb]);else if(a[B]==1&&(a[K]=="INPUT"||a[K]=="TEXTAREA"))b=a[Xa];else if(a[I]&&!a[I][Jb]&&a[I][B]==3)b=ha(a[I][Nb]);return b}function Lf(a,b){if(a)if(a[B]==3)a.nodeValue=b;else if(a[B]==1)if(a[K]=="INPUT"||a[K]=="TEXTAREA")qa(a,b);else W.na(a,b)}function Mf(a,b){return a[yb](0,a[x]-Qc(a)[x])+Pc(b)+a[yb](Rc(a)[x])}function Nf(a,b){return function(){a[cb](b)}}
function Of(a){a=Pc(a).toLowerCase()[A]("_","-");if(a=="zh-cn")return"zh-CN";else if(a=="zh-tw")return"zh-TW";var b=a[C]("-");a=b>=0?a[yb](0,b):a;if(a=="zh")return"zh-CN";return a}function Pf(a){var b=[];for(var c in a)if(a[c]!==m[y][c]){var d=Tc(c);if(Ub(a[c])=="array")for(var e=0;e<a[c][x];++e)b[s](d+"="+Tc(a[c][e]));else b[s](d+"="+Tc(a[c]))}return b[N]("&")}function Qf(a,b){b=b||{};b.nca=a;b.client=ic;var c=new Image;c.src="http://"+qc+"/gen204?"+Pf(b);c.onload=function(){c.onload=j}};function Rf(a,b){Z[G](this,b);this.a=a||{};this.a.C||(this.a.C=pc);this.a.ba=this.a.ba;this.a.ab=!!this.a.ab;this.e=new cf(this)}U(Rf,Z);P=Rf[y];P.z=function(){this.f=this.m[H]("div");this.f[D].position="absolute";this.f[D].zIndex=1073741824;this.f[D].top="-9999em";this.g=k;var a={id:$(this,"container")};pa(this.f,zf(a))};
P.W=function(){Rf.A.W[G](this);var a={C:this.a.C,dir:nf[Ha](ec)?"rtl":"ltr",ta:oc,Kb:V&&!Hd("7.0"),hb:sc,Lb:kc};this.f.id=$(this,"balloonContainer");this.c=this.m.l($(this,"container"));Y(this.e,this.c,"load",this.Zd);var b=W.Z(this.c);b[gb](Af(a));b[db]()};
P.Zd=function(){X(this.f,i);var a=new Od(W.Z(this.c));this.b=a;this.j=a.l("content");this.s=a.l("original");var b=V?this.c:W.Wa(this.c);Y(this.e,b,"mouseout",this.Ad);Y(this.e,b,"mouseover",this.Bd);Y(this.e,a.l("close"),"click",Nf(this,"close"));if(V)na(this.j[D],"100%");this.a.ab||X(a.l("logo"),k);this.h=200;if(this.a.ba!=0){this.d=a.l("suggestForm");this.d.action="http://translate.google.com/translate_suggestion";Y(this.e,this.d,"submit",this.td);if(this.a.ba==1){this.k=a.l("zippy_img");this.B=
a.l("feedback");a=a.l("zippy");Y(this.e,a,"click",this.Fc);X(a,i);for(a=a[I];a;a=a[Jb])this.h+=a[Va]}else if(this.a.ba==2){ua(this.d,"_blank");X(a.l("forward"),i);Y(this.e,a.l("forward_link"),"click",T(this.d.submit,this.d))}}X(this.f,k);this[cb]("load")};P.J=function(){Rf.A.J[G](this);this.e.t();this.b=this.e=j;W[Bb](this.c);this.B=this.k=this.d=this.s=this.j=this.c=j};
P.Fc=function(){if(this.k[Ka]=="plus"){ma(this.k,"minus");X(this.d[L],i);this[cb]("open_form")}else{ma(this.k,"plus");X(this.d[L],k);this[cb]("close_form")}Sf(this)};P.Ad=function(){this[cb]("mouseout")};P.Bd=function(){this[cb]("mouseover")};P.td=function(){this.a.ba==1&&this.Fc()};function Tf(a,b,c,d,e,f,h){W.na(a.s,Pc(b));if(a.d){qa(a.d.gtrans,c||"");qa(a.d[Na],b||"");qa(a.d.langpair,d+"|"+e);qa(a.d.u,f||"");qa(a.d.client,h||"");qa(a.d.utrans,Pc(c||""))}}
function Sf(a){var b=Xe(a.j);if(b[z]<a.h)na(b,a.h);if(b[M]<=0)Ba(b,a.h);Ye(a.c,b);Ye(a.f,b)}Rf[y].reset=function(a){this.f[D].top="-9999em";X(this.f,i);var b=this.b[H]("span");b[p](this.s[I].cloneNode(i));b[D].whiteSpace="nowrap";this.j[p](b);var c=b[Va]+20;this.j[ib](b);b=this.m.o()[E][Va]/2;if(a&&c>a)c=a;if(c>b)c=b;if(c<this.h)c=this.h;na(this.c[D],c+"px");Sf(this);if(this.a.ba==1){ma(this.k,"plus");X(this.d[L],k);X(this.B,k)}};Rf[y].ca=Pb("g");
Rf[y].O=function(a,b,c){if(a){if(b){var d=0,e=0,f=0;if(c&&c[x]){for(var h=NaN,n=NaN,q=NaN,r=NaN,t=0;t<c[x];++t){var w=Ue(c[t]);if(w[z]&&w[M]){h<w[F]||(h=w[F]);n>w[F]+w[z]||(n=w[F]+w[z]);q<w.top||(q=w.top);r>w.top+w[M]||(r=w.top+w[M])}}this.reset(n-h);if(h&&q&&r){w=Ue(b);d=h-w[F];e=q-w.top;f=w.top+w[M]-r}}else this.reset();c=lf(b,4,this.f,5,new Fc(d||0,-4+(e||0)),ca,9);if(c&496)lf(b,5,this.f,4,new Fc(d||0,-4+(f||0)),ca,5)}}else X(this.f,a);this.g=a};function Uf(a,b){this.a=a||{};this.a.ba=a.formMode;this.a.ab=!!a.showLogo;this.a.bd=ea(a.delayMs,10)||300;this.a.Md=a.pageUrl;this.a.Xc=a.clientName;this.j=0;this.e={};this.d=k;this.c=new cf(this);this.g=j;this.b=new Rf({C:pc,ba:this.a.ba,ab:this.a.ab},b);this.b.la((b||W).o()[E]);Y(this.c,this.b,"open_form",this.G);Y(this.c,this.b,"close_form",this.B);Y(this.c,this.b,"mouseout",this.k);Y(this.c,this.b,"mouseover",this.I);Y(this.c,this.b,"close",this.K);this.h=""}U(Uf,uc);
function Vf(a,b,c){b&&(a.r=b);c&&(a.s=c)}function Wf(a,b,c,d,e,f){a.e[++a.j]={text:c,ce:d,Xd:e||a.r,be:f||a.s,ga:b};for(c=0;c<b[x];++c)if(b[c]){Y(a.c,b[c],"mouseout",a.k);Y(a.c,b[c],"mouseover",T(a.Y,a,a.j,b[c]))}return(a.j-1)[v]()}function Xf(a,b){var c=a.e[b];if(c){for(var d=0;d<c.ga[x];++d)if(c.ga[d]){ef(a.c,c.ga[d],"mouseout");ef(a.c,c.ga[d],"mouseover")}delete a.e[b]}}function Yf(a){Zf(a);for(var b in a.e)Xf(a,b)}Uf[y].D=function(){Yf(this);this.c.t();this.c=j;this.b.t();this.b=j};
function $f(a){if(a.g){l[La](a.g);a.g=j}}function ag(a,b){$f(a);a.g=l[Sa](T(function(c){c[G](this);this.g=j},a,b),a.a.bd)}Uf[y].G=function(){this.d=i};Uf[y].B=function(){$f(this);this.d=k};function bg(a,b,c){if(a=a.e[b]){c=c||typeof c=="undefined";for(b=0;b<a.ga[x];++b)if(a.ga[b]){Fe(a.ga[b],"backgroundColor",c?"#E6ECF9":"");Fe(a.ga[b],"color",c?"#000":"")}}}Uf[y].k=function(){this.d||ag(this,function(){bg(this,this.h,k);this.b.O(k);this.d=k})};Uf[y].I=function(){this.d||$f(this)};
function Zf(a){a.d=i;$f(a);bg(a,a.h,k);a.b.O(k);a.d=k}Uf[y].K=function(){Zf(this)};Uf[y].Y=function(a,b){this.d||ag(this,function(){bg(this,this.h,k);this.h=a;bg(this,a);var c=this.e[a];this.a.ba!=0?Tf(this.b,c[Na],c.ce,c.Xd,c.be,this.a.Md,this.a.Xc):Tf(this.b,c[Na]);this.b.O(i,b,c.ga);this.d=k})};function cg(a,b,c,d,e){this.a=a;this.yb=b;this.r=d;this.j=c;this.g=e;this.h=new Array(this.a[x]);this.b=new Array(this.a[x]);this.c=[];this.d=[];this.e=this.k=k}U(cg,uc);
function dg(a,b){a.k=i;a.c=[];var c=W[H]("div");X(c,k);pa(c,b[C]("<i>")>=0?b:"<b>"+b+"</b>");W.o()[E][p](c);b=j;for(var d=c[I];d;d=d[Jb])if(d[K]==Kd)a.c[s](b={Kc:W.pa(d),X:[]});else if(d[K]==Jd){b||a.c[s](b={Kc:"",X:[]});if(a.a[x]==1)b.X[s]({index:0,text:$c(W.pa(d))});else{for(var e={},f=-1,h=d[I];h;h=h[Jb])if(h.attributes&&h.attributes.i){f=ea(h.attributes.i[Nb],10);if(f!=NaN){e[f]||(e[f]="");e[f]+=W.pa(h)}}else if(h[B]==3){e[f]||(e[f]="");e[f]+=h[Nb]}for(f in e)f>=0&&f<a.a[x]&&b.X[s]({index:f,text:$c(e[f])});
if(e[-1])if(b.X[x]==0&&e[-1])b.X[s]({index:0,text:$c(e[-1])});else b.X[0].text=$c(e[-1])+b.X[0][Na]}b=j}c[L][ib](c);eg(a)}cg[y].restore=function(){if(this.e){this.e=k;if(this.d[x]>0){for(var a=0;a<this.d[x];++a)Xf(this.g,this.d[a]);this.d=[]}for(a=0;a<this.a[x];++a)if(this.h[a]){Lf(this.a[a],this.j[a]);if(this.b[a]){var b=this.b[a];this.a[a]=b[I];W.Cb(b);this.b[a]=j}this.h[a]=k}}};
function eg(a){function b(u,sa){return u[hb]?u[hb][Wa](sa):W[Wa](sa)}function c(u){u.background="transparent";u.border="0";u.fontSize="100%";u.margin="0";u.outline="0";u.padding="0";u.verticalAlign="baseline";Aa(u,"inline")}if(!(!a.k||a.e)){a.e=i;for(var d=0;d<a.a[x];++d)if(!a.h[d]){var e=a.a[d];if(e[L]&&(e[L][K]=="OPTION"||e[L][K]=="TITLE")||e[K]=="INPUT"||e[K]=="TEXTAREA"){Lf(a.a[d],"");a.b[d]=j}else{var f=e[hb]?e[hb][H]("span"):W[H]("span");c(f[D]);W.replaceNode(f,e);a.b[d]=f;a.a[d]=f}a.h[d]=i}for(d=
0;d<a.c[x];++d){var h=a.c[d],n=h.Kc;if(!n){for(var q=[],r=0;r<h.X[x];++r)q[s](a.j[h.X[r][Ma]]);n=q[N](" ")}var t=[];q=[];for(r=0;r<h.X[x];++r){q[s](h.X[r][Na]);var w=h.X[r];if(e=a.b[w[Ma]]){f=e[hb]?e[hb][H]("span"):W[H]("span");t[s](f);c(f[D]);a.g||(f.title=n);Lf(f,w[Na]);W[p](e,f);d!=0&&e[I]!=f&&W.Ob(b(f," "),f)}else Lf(a.a[w[Ma]],Kf(a.a[w[Ma]])+w[Na])}a.g&&a.d[s](Wf(a.g,t,n,q[N]("")))}for(d=0;d<a.a[x];++d){e=a.b[d];f=a.j[d];if(e){for(h=e[I];h;h=h[Jb]){n=Qc(Kf(h));Lf(h,n);if(n)break}for(h=e[mb];h;h=
h[Ea]){n=Rc(Kf(h));Lf(h,n);if(n)break}h=f[yb](0,f[x]-Qc(f)[x]);(n=e[I])?Lf(n,h+Kf(n)):W[p](e,b(e,h));n=e[mb];h=f[yb](Rc(f)[x]);n?Lf(n,Kf(n)+h):W[p](e,b(e,h))}else Lf(a.a[d],Mf(f,Kf(a.a[d])))}}}cg[y].D=function(){cg.A.D[G](this);this[Cb]();this.a=j};function fg(a){Z[G](this,a);this.g=new cf(this)}U(fg,Z);fg[y].z=function(){this.f=this.m[H]("select");ma(this.f,"goog-te-combo")};fg[y].W=function(){fg.A.W[G](this);this.ic()};fg[y].ic=function(){se(this.f,"change",Nf(this,"chg_lang"));this[cb]("load")};function hg(a,b){if(a.f[L]!=b){a.f[L][ib](a.f);b[p](a.f)}}P=fg[y];P.$a=function(a){this.m.Ia(this.f);for(var b in a)if(a[b]!==m[y][b]){var c=this.m.z("option",{value:b});this.m.na(c,a[b]);W[p](this.f,c)}this.f.selectedIndex=0};P.lb=function(){return this.f[Xa]};
P.oa=function(a){if(this.f[Xa]!=a)for(var b=0,c;c=this.f.options[Za](b);++b)if(c[Xa]==a){this.f.selectedIndex=b;return}};P.Fb=function(a){if(Ub(a)=="undefined")return this.f.options[Za](this.f.selectedIndex)[Na];for(var b=0,c;c=this.f.options[Za](b);++b)if(c[Xa]==a)return c[Na]};P.J=function(){fg.A.J[G](this);this.g.t();this.g=j};function ig(a,b){fg[G](this,b);this.a=a||{};this.a.C||(this.a.C=pc)}U(ig,fg);P=ig[y];
P.z=function(){this.f=this.m[H]("a");ma(this.f,"goog-te-menu-value");ya(this.f,"javascript:void(0)");this.s=this.m[H]("span");this.f[p](this.s);this.e=this.m.z("img",{src:sc,style:"background-image:url("+kc+");background-position:-14px 0px;border:none",width:14,height:14});this.f[p](this.e);this.c=W.z("iframe",{frameBorder:0,"class":"goog-te-menu-frame skiptranslate"});this.c[D].visibility="visible";X(this.c,k);W.o()[E][p](this.c)};
P.ic=function(){var a={dir:nf[Ha](ec)?"rtl":"ltr",C:this.a.C,id:$(this,"menuBody")};Y(this.g,this.c,"load",this.Yd);var b=W.Z(this.c);b[gb](qf(a));b[db]()};P.Yd=function(){this.b=new Od(W.Z(this.c));this.h=this.b.l($(this,"menuBody"));Y(this.g,this.f,"click",this.rd);V?Y(this.g,this.c,"blur",this.Jb):Y(this.g,W.Wa(this.c),"blur",this.Jb);this[cb]("load")};P.$a=function(){};P.zd=function(a){if(this.j!=a[fb][Xa]){this.oa(a[fb][Xa]);this[cb]("chg_lang")}this.Jb()};
P.rd=function(){this.rb();W.Wa(this.c).focus();this.B=i};P.Jb=function(){if(this.B){this.B=k;this.rb(k)}};P.rb=function(a){if(a==k){Fe(this.e,"backgroundPosition","-14px 0px");X(this.c,k)}else{a=Qe(this.e,l);a.y+=this.e[Lb];a.x+=this.e[Va]-this.I[z]>>1;if(V&&!Hd("7.0")){var b=W.o()[E];a.y-=b.offsetTop;a.x-=b.offsetLeft}else{b=W.xa();a.y-=b.y;a.x-=b.x}if(a.x<0)a.x=0;Ke(this.c,a);Fe(this.e,"backgroundPosition","0px 0px");X(this.c,i)}};P.lb=Pb("j");
P.oa=function(a){if(this.j!=a){var b=this.Fb(a);if(b){this.j=a;this.m.na(this.s,b)}}};P.Fb=function(){};P.J=function(){ig.A.J[G](this);W[Bb](this.c);this.h=this.b=this.c=this.e=this.s=j};function jg(a,b){ig[G](this,a,b);this.a=a||{};this.a.C||(this.a.C=pc)}U(jg,ig);
jg[y].$a=function(a){this.b.Ia(this.h);X(this.c,i);this.K=a;this.d=[];for(var b in a)if(a[b]!==m[y][b]){var c={Ea:this.b.z("a",{className:"goog-te-menu2-item-selected",href:"javascript:void(0)",value:b})};this.d[s](c);var d=this.b.z("div",{style:"white-space:nowrap"});this.b[p](c.Ea,d);this.b[p](d,this.b.z("span",{className:"indicator"},"\u203a"));this.b[p](d,this.b.z("span",{className:"text"},a[b]));Y(this.g,c.Ea,"click",this.zd)}a=this.d[x]-1;a=o[Qa]((a-a%11)/11)+1;this.k=this.b.z("table",{cellspacing:0,
cellpadding:0,border:0});c=this.b.z("tbody");b=this.b.z("tr",{valign:"top"});ma(this.h,"goog-te-menu2");this.b[p](this.h,this.k);this.b[p](this.k,c);this.b[p](c,b);for(d=c=0;c<a;++c){var e=this.b.z("td");this.b[p](b,e);for(var f=0;f<11&&d<this.d[x];++f,++d)this.b[p](e,this.d[d].Ea);if(c!=a-1){e=this.b.z("td",{"class":"goog-te-menu2-colpad"},"\u00a0");this.b[p](b,e)}}this.j="";this.oa(this.d[0].Ea[Xa]);kg(this);X(this.c,k)};jg[y].Fb=function(a){a=Ub(a)=="undefined"?this.j:a;return this.K[a]};
jg[y].oa=function(a){if(this.j!=a){jg.A.oa[G](this,a);for(var b=0;b<this.d[x];++b){var c=this.d[b];ma(c.Ea,c.Ea[Xa]==a?"goog-te-menu2-item-selected":"goog-te-menu2-item")}}};function kg(a){Ye(a.h,Xe(a.k));Ye(a.c,Xe(a.h));a.I=Xe(a.c)}jg[y].rb=function(a){jg.A.rb[G](this,a);a!=k&&kg(this)};jg[y].J=function(){jg.A.J[G](this);this.k=this.d=j};function lg(a){return a="Desactivar traducci\u00f3n del "+a};var mg="StopIteration"in Q?Q.StopIteration:aa("StopIteration");function ng(){}ng[y].c=function(){g(mg)};ng[y].e=function(){return this};function og(a,b,c,d,e){this.a=!!b;a&&this[Hb](a,d);this.b=e!=ca?e:this.S||0;if(this.a)this.b*=-1;this.d=!c}U(og,ng);P=og[y];P.M=j;P.S=j;P.Wb=k;P.setPosition=function(a,b,c){if(this.M=a)this.S=typeof b=="number"?b:this.M[B]!=1?0:this.a?-1:1;if(typeof c=="number")this.b=c};P.L=function(){return new og(this.M,this.a,!this.d,this.S,this.b)};function pg(a){var b=a.a?-1:1;if(a.S==b){a.S=b*-1;a.b+=a.S*(a.a?-1:1)}}
og[y].c=function(){var a;if(this.Wb){if(!this.M||this.d&&this.b==0)g(mg);a=this.M;var b=this.a?-1:1;if(this.S==b){var c=this.a?a[mb]:a[I];c?this[Hb](c):this[Hb](a,b*-1)}else(c=this.a?a[Ea]:a[Jb])?this[Hb](c):this[Hb](a[L],b*-1);this.b+=this.S*(this.a?-1:1)}else this.Wb=i;a=this.M;if(!this.M)g(mg);return a};
og[y].splice=function(){var a=this.M,b=this.a?1:-1;if(this.S==b){this.S=b*-1;this.b+=this.S*(this.a?-1:1)}this.a=!this.a;og[y].c[G](this);this.a=!this.a;b=Vb(arguments[0])?arguments[0]:arguments;for(var c=b[x]-1;c>=0;c--)W.Nb(b[c],a);W[Bb](a)};function qg(a,b){this.a=new og;this.s=a;this.I=b}var rg=Bf([Id,"ABBR","ACRONYM",Jd,"BASEFONT","BDO","BIG","CITE","CODE","DFN","EM","FONT",Kd,"KBD","LABEL",Ld,Md,"SMALL","SPAN","STRIKE","STRONG","SUB","SUP","TT",Nd,"VAR"]),sg=Bf(["APPLET","AREA","BASE","FRAME","FRAMESET","HR","IMG","LINK","META","MAP","OBJECT","PARAM","SCRIPT","STYLE","INPUT","TEXTAREA"]),tg=Bf(["submit","button"]);qg[y].reset=function(a,b){this.g=[];this.j=[];this.B=i;this.h=[];this.r=[];ug(this,a,i,b)};
function ug(a,b,c,d){a.a[Hb](b,1,1);a.k=i;a.c=0;a.d=[c];a.e=!!d;a.a.Wb||a.a.c();vg(a)}
function wg(a,b){if(a.k){var c=0,d=[],e=[],f=0,h=[],n=a.e?27:13;do{var q=a.G;f+=a.c||(a.c=(a.e?Tc(q)[x]:q[x])+n);if(c!=0&&f>b)break;a.c=0;d[s](a.K);h[s](a.b);if(c==0){e[s](q);c++}else{if(c==1)e[0]="<a i=0>"+e[0]+"</a>";e[s]("<a i="+c++ +">");e[s](q);e[s]("</a>")}}while(vg(a));return new cg(d,e[N](""),h,(d[x]==1?f-n:f)-a.c,a.I)}else if(a.g[x]>0){ug(a,a.g[Ia](),a.j[Ia](),a.e);return wg(a,b)}else if(a.h[x]>0){a.B=k;ug(a,a.h[Ia](),a.r[Ia](),a.e);return wg(a,b)}}function xg(a){return a.d[a.d[x]-1]}
function vg(a){var b=i;try{for(;;){var c=a.K=a.a.M,d=a.a.S;if(d==-1){a.d.pop();b=b&&!!a.a.M&&(a.a.M[B]==3||rg[a.a.M[K]])}else if(c&&(c[B]==3||c[K]=="TEXTAREA"&&W.n.ra(c,"translate")||c[K]=="INPUT"&&(tg[c[Db]]||W.n.ra(c,"translate")))){pg(a.a);if(xg(a)){a.b=Kf(c);var e=Pc(a.b[A](/\xa0|[ \t]+/g," "));e||(a.b=e);if(a.b){a.G=Uc(a.b);a.a.c();break}}}else if(d==1){if(yg(a,c))pg(a.a);else if(c[K]=="IFRAME"){pg(a.a);try{var f=c[Kb][Ta][Ob];if(f){a.g[s](f);a.j[s](xg(a))}}catch(h){}}else if(a.B&&!(c[Va]&&c[Lb])){pg(a.a);
a.h[s](c);a.r[s](xg(a))}else{var n=a,q=c,r=!W.n.ra(q,"notranslate")&&(W.n.ra(q,"translate")||xg(n));n.d[s](r)}b=b&&xg(a)&&!!a.a.M&&(a.a.M[B]==3||rg[a.a.M[K]]);a.s&&xg(a)&&c[K]==Id&&c[xb]&&a.s(c)}a.a.c()}}catch(t){if(t!=mg)g(t);a.k=k;a.b=j;b=k}return b}function yg(a,b){return b[B]!=3&&(!b[K]||sg[b[K]]||W.n.ra(b,"skiptranslate"))};function zg(a,b){Z[G](this,b);this.e=new cf(this);this.a=a||{};this.a.C||(this.a.C=pc);this.a.Vb=k;Fe(this.m.o()[E],"position","relative");Fe(this.m.o()[E],"top","0px");if(V){l._bannerquirkfixleft=-ea("0"+this.m.o()[E].leftMargin,10);l._bannerquirkfixtop=-ea("0"+this.m.o()[E].topMargin,10)-40}}U(zg,Z);P=zg[y];P.la=function(){var a=this.m.o()[E][I];kf(this,a[L],a)};P.z=function(){this.f=this.m[H]("div");this.g=k;X(this.f,k);W.n.add(this.f,"skiptranslate");var a={id:$(this,"container")};pa(this.f,rf(a))};
P.W=function(){zg.A.W[G](this);var a={dir:nf[Ha](ec)?"rtl":"ltr",C:this.a.C,hb:sc,Qb:"http://translate.google.com",ta:tc,Lb:kc,Sd:$(this,"promptSection"),Zc:$(this,"confirm"),Gd:"http://www.google.com/intl/en/help/faq_translation.html#element",Qd:$(this,"progressSection"),Pd:$(this,"progressValue"),Hd:nc,Wc:$(this,"cancel"),jd:$(this,"finishSection"),Td:$(this,"restore"),gd:$(this,"errorSection"),fd:$(this,"errorContent"),Yc:$(this,"close"),me:kc,Ld:$(this,"noAutoPopup")},b=[];this.a.Vb&&b[s](uf({id:$(this,
"promptSourceLang")}));b[s](uf({id:$(this,"promptTargetLang")}));b=b="\u00bfQuieres traducir esta p\u00e1gina al "+(b+" con el Traductor de Google?");a.Rd=b;b=[];this.a.Vb&&b[s](uf({id:$(this,"finishSourceLang")}));b[s](uf({id:$(this,"finishTargetLang")}));b=b="Google ha traducido esta p\u00e1gina autom\u00e1ticamente al "+(b+".");a.hd=b;this.a.va&&(a.va=this.a.va);this.c=this.m.l($(this,"container"));Y(this.e,this.c,"load",this.$d);b=W.Z(this.c);b[gb](sf(a));b[db]()};
P.$d=function(){this.b=new Od(W.Z(this.c));pa(this.b.l($(this,"errorContent")),"Error: el servidor no ha podido completar la solicitud. Vuelve a intentarlo m\u00e1s tarde.");this.a.C==pc&&Fe(this.b.o()[E],"backgroundImage","url("+jc+")");if(this.a.Vb)this.H=new jg(this.a,this.b);this.d=new jg(this.a,this.b);Y(this.e,this.b.l($(this,"confirm")),"click",Nf(this,"clk_confirm"));Y(this.e,this.b.l($(this,"cancel")),"click",Nf(this,"clk_cancel"));Y(this.e,this.b.l($(this,"restore")),"click",Nf(this,"clk_restore"));
Y(this.e,this.b.l($(this,"close")),"click",Nf(this,"clk_close"));this.h=this.b.l($(this,"noAutoPopup"));Y(this.e,this.h,"click",Nf(this,"clk_no_ap"));this.H&&Y(this.e,this.H,"chg_lang",Nf(this,"chg_src_lang"));Y(this.e,this.d,"chg_lang",Nf(this,"chg_tgt_lang"));var a=new Df(T(this[cb],this,"load"));this.H&&Y(this.e,this.H,"load",Ef(a));Y(this.e,this.d,"load",Ef(a));a.Sa();this.H&&this.H.la(this.b.l($(this,"promptSourceLang")));this.d.la(this.b.l($(this,"promptTargetLang")))};
P.J=function(){this.O(k);zg.A.J[G](this);this.e.t();this.e=j;if(this.H){this.H.t();this.H=j}this.d.t();this.d=j;W[Bb](this.c);this.Qa=this.b=j};P.za=function(){return this.d.lb()};P.Ub=function(a){this.d.$a(a)};function Ag(a,b){a.H&&a.H.oa(b);a.j&&a.j[b]&&a.b.na(a.h,lg(a.j[b]))}zg[y].aa=function(a){this.d.oa(a)};
function Bg(a,b,c,d){if(a.Qa!=b){a.Qa=b;if(b==0){a.H&&hg(a.H,a.b.l($(a,"promptSourceLang")));hg(a.d,a.b.l($(a,"promptTargetLang")))}else if(b==2){a.H&&hg(a.H,a.b.l($(a,"finishSourceLang")));hg(a.d,a.b.l($(a,"finishTargetLang")))}var e={};e[-1]=a.b.l($(a,"errorSection"));e[0]=a.b.l($(a,"promptSection"));e[1]=a.b.l($(a,"progressSection"));e[2]=a.b.l($(a,"finishSection"));for(var f in e)e[f]!==m[y][f]&&X(e[f],f==b)}c&&a.O(i);Aa(a.h[D],d?"block":"none")}zg[y].ca=Pb("g");
zg[y].O=function(a){if(this.g!=a){this.g=a;if(V)var b=ea("0"+this.m.o()[E].leftMargin,10),c=ea("0"+this.m.o()[E].topMargin,10);var d=this.m.o().compatMode=="BackCompat";if(a){Fe(this.m.o()[E],"top","40px");X(this.f,i);if(V)if(Hd("7.0")){l._bannerquirkfixleft=l._bannerquirkfixtop=0;if(d)this.m.o()[E].topMargin=c+40}else if(d){this.k=i;this.m.o()[E].topMargin=c+40;l._bannerquirkfixleft=l._bannerquirkfixtop=0}else{l._bannerquirkfixleft=-b;l._bannerquirkfixtop=-c-40}}else{Fe(this.m.o()[E],"top","0px");
X(this.f,k);if(d&&c>=40)this.m.o()[E].topMargin=c-40}}};function Cg(a,b){a.b.na(a.b.l($(a,"progressValue")),b)};function Dg(a){Z[G](this,a);this.a=new cf(this)}U(Dg,Z);P=Dg[y];
P.z=function(){this.f=this.m[H]("div");W.n.add(this.f,"skiptranslate");W.n.add(this.f,"goog-te-gadget");X(this.f,k);var a;a={Kb:V&&!Hd("7.0"),ta:oc,Qb:"http://translate.google.com",translate:"Traductor de Google"};var b=new pf;b.F('<span style="white-space:nowrap"><a class="goog-logo-link" href="',a.Qb,'" target="_blank">',a.Kb?"<span style=\"display:inline-block;vertical-align:middle;height:15px; width:51px;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='"+a.ta+"',sizingMethod='scale');\"></span>":
'<img src="'+a.ta+'">',"Traducir","</a></span>");a=b[v]();a=a="Con la tecnolog\u00eda de "+a;pa(this.f,vf({id:$(this,"targetLanguage"),Od:a}))};P.W=function(){Dg.A.W[G](this);this.d=new fg(this.m);Y(this.a,this.d,"chg_lang",Nf(this,"chg_tgt_lang"));Y(this.a,this.d,"load",this.xd);this.d.la(this.m.Xb($(this,"targetLanguage")))};P.xd=function(){this[cb]("load")};P.J=function(){Dg.A.J[G](this);this.a.t();this.a=j;this.d.t();this.d=j};P.za=function(){return this.d.lb()};P.Ub=function(a){this.d.$a(a)};
P.aa=function(a){this.d.oa(a)};P.O=function(a){X(this.f,a)};function Eg(a,b){Z[G](this,b);this.a=a||{};this.a.C||(this.a.C=pc);this.b=new cf(this)}U(Eg,Z);var Fg={ie:1,je:2,ge:3,fe:4};P=Eg[y];P.z=function(){this.f=this.m[H]("div");this.g=k;X(this.f,k);var a={id:$(this,"container")};pa(this.f,wf(a))};
P.W=function(){Eg.A.W[G](this);var a={dir:nf[Ha](ec)?"rtl":"ltr",C:this.a.C,de:$(this,"translate")};this.f.id=$(this,"floatContainer");var b={id:this.f.id,className:"goog-te-ftab-float"};this.f.className+=" goog-te-ftab-float";switch(this.a.Ta){case 2:a.jb="goog-float-top";b.top=0;Ca(b,20);break;case 3:a.jb="goog-float-bottom";xa(b,0);Ca(b,20);break;case 4:a.jb="goog-float-bottom";xa(b,0);ta(b,20);break;case 1:default:a.jb="goog-float-top";b.top=0;ta(b,20);break}b=b;var c=new pf;c.F(".",b[Ka]," {z-index:9999999; overflow:visible; position:fixed; _position:absolute;",
b.top||b.top==0?"top:"+b.top+"px; _top:expression(("+b.top+"+(hack1=document.documentElement.scrollTop||document.body.scrollTop))+'px');":"top:auto;",b[F]||b[F]==0?"left:"+b[F]+"px; _left:expression(("+b[F]+"+(hack2=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"left:auto;",b[J]||b[J]==0?"bottom:"+b[J]+"px; _top:expression((-"+b[J]+"-document.getElementById('"+b.id+"').offsetHeight+(hack3=document.documentElement.clientHeight||document.body.clientHeight)+(hack4=document.documentElement.scrollTop||document.body.scrollTop))+'px');":
"bottom:auto;",b[O]||b[O]==0?"right:"+b[O]+"px; _left:expression((-"+b[O]+"-document.getElementById('"+b.id+"').offsetWidth+(hack5=document.documentElement.clientWidth||document.body.clientWidth)+(hack6=document.documentElement.scrollLeft||document.body.scrollLeft))+'px');":"right:auto;","}");b=c[v]();c=W.P(this.f);var d=j;if(V){d=c.o().createStyleSheet();We(d,b)}else{var e=c.Va("head")[0];if(!e){d=c.Va("body")[0];e=c.z("head");d[L][$a](e,d)}d=c.z("style");We(d,b);c[p](e,d)}this.c=this.m.l($(this,
"container"));Y(this.b,this.c,"load",this.ae);b=W.Z(this.c);b[gb](xf(a));b[db]()};P.ae=function(){var a=new Od(W.Z(this.c));this.d=a.l($(this,"translate"));Y(this.b,this.d,"click",Nf(this,"clk_trans"));X(this.f,i);a=Xe(this.d);X(this.f,k);Ye(this.c,a);Ye(this.f,a);this[cb]("load")};P.J=function(){Eg.A.J[G](this);this.b.t();this.b=j;W[Bb](this.c);this.d=this.c=j};P.ca=Pb("g");P.O=function(a){this.g=a;X(this.f,a)};function Gg(a){if(typeof a.qa=="function")return a.qa();if(S(a))return a[Ua]("");if(Vb(a)){for(var b=[],c=a[x],d=0;d<c;d++)b[s](a[d]);return b}return Jc(a)}function Hg(a,b,c){if(typeof a[rb]=="function")a[rb](b,c);else if(Vb(a)||S(a))xc(a,b,c);else{var d;var e=a;if(typeof e.ya=="function")d=e.ya();else if(typeof e.qa!="function")if(Vb(e)||S(e)){d=[];e=e[x];for(var f=0;f<e;f++)d[s](f);d=d}else d=Kc(e);else d=void 0;e=Gg(a);f=e[x];for(var h=0;h<f;h++)b[G](c,e[h],d&&d[h],a)}};function Ig(a){this.b={};this.a=[];var b=arguments[x];if(b>1){if(b%2)g(aa("Uneven number of arguments"));for(var c=0;c<b;c+=2)this.ea(arguments[c],arguments[c+1])}else a&&Jg(this,a)}P=Ig[y];P.p=0;P.cb=0;P.qa=function(){Kg(this);for(var a=[],b=0;b<this.a[x];b++){var c=this.a[b];a[s](this.b[c])}return a};P.ya=function(){Kg(this);return this.a.concat()};P.ja=function(a){return Lg(this.b,a)};P.clear=function(){this.b={};la(this.a,0);this.cb=this.p=0};
P.remove=function(a){if(Lg(this.b,a)){delete this.b[a];this.p--;this.cb++;this.a[x]>2*this.p&&Kg(this);return i}return k};function Kg(a){if(a.p!=a.a[x]){for(var b=0,c=0;b<a.a[x];){var d=a.a[b];if(Lg(a.b,d))a.a[c++]=d;b++}la(a.a,c)}if(a.p!=a.a[x]){var e={};for(c=b=0;b<a.a[x];){d=a.a[b];if(!Lg(e,d)){a.a[c++]=d;e[d]=1}b++}la(a.a,c)}}Ig[y].N=function(a,b){if(Lg(this.b,a))return this.b[a];return b};Ig[y].ea=function(a,b){if(!Lg(this.b,a)){this.p++;this.a[s](a);this.cb++}this.b[a]=b};
function Jg(a,b){var c;if(b instanceof Ig){c=b.ya();b=b.qa()}else{c=Kc(b);b=Jc(b)}for(var d=0;d<c[x];d++)a.ea(c[d],b[d])}Ig[y].L=function(){return new Ig(this)};Ig[y].e=function(a){Kg(this);var b=0,c=this.a,d=this.b,e=this.cb,f=this,h=new ng;h.c=function(){for(;;){if(e!=f.cb)g(aa("The map has changed since the iterator was created"));if(b>=c[x])g(mg);var n=c[b++];return a?n:d[n]}};return h};function Lg(a,b){return m[y][ab][G](a,b)};var Mg=new RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Ng(a){return a.match(Mg)};function Og(a,b){var c;if(a instanceof Og){Pg(this,b==j?a.Aa:b);Qg(this,a.ma);Rg(this,a.bb);Sg(this,a.Ra);Tg(this,a.Ha);Ug(this,a.Ya);Vg(this,a.a.L());Wg(this,a.Ua)}else if(a&&(c=Ng(ha(a)))){Pg(this,!!b);Qg(this,c[1]||"",i);Rg(this,c[2]||"",i);Sg(this,c[3]||"",i);Tg(this,c[4]);Ug(this,c[5]||"",i);Vg(this,c[6]||"",i);Wg(this,c[7]||"",i)}else{Pg(this,!!b);this.a=new Xg(j,this,this.Aa)}}P=Og[y];P.ma="";P.bb="";P.Ra="";P.Ha=j;P.Ya="";P.Ua="";P.Ed=k;P.Aa=k;
ka(P,function(){if(this.U)return this.U;var a=[];this.ma&&a[s](Yg(this.ma,Zg),":");if(this.Ra){a[s]("//");this.bb&&a[s](Yg(this.bb,Zg),"@");a[s]($g(this.Ra));this.Ha!=j&&a[s](":",ha(this.Ha))}this.Ya&&a[s](Yg(this.Ya,ah));var b=ha(this.a);b&&a[s]("?",b);this.Ua&&a[s]("#",Yg(this.Ua,bh));return this.U=a[N]("")});
P.L=function(){var a;a=this.ma;var b=this.bb,c=this.Ra,d=this.Ha,e=this.Ya,f=this.a.L(),h=this.Ua,n=new Og(j,this.Aa);a&&Qg(n,a);b&&Rg(n,b);c&&Sg(n,c);d&&Tg(n,d);e&&Ug(n,e);f&&Vg(n,f);h&&Wg(n,h);return a=n};function Qg(a,b,c){ch(a);delete a.U;a.ma=c?b?ja(b):"":b;if(a.ma)a.ma=a.ma[A](/:$/,"");return a}function Rg(a,b,c){ch(a);delete a.U;a.bb=c?b?ja(b):"":b;return a}function Sg(a,b,c){ch(a);delete a.U;a.Ra=c?b?ja(b):"":b;return a}
function Tg(a,b){ch(a);delete a.U;if(b){b=Number(b);if(isNaN(b)||b<0)g(aa("Bad port number "+b));a.Ha=b}else a.Ha=j;return a}function Ug(a,b,c){ch(a);delete a.U;a.Ya=c?b?ja(b):"":b;return a}function Vg(a,b,c){ch(a);delete a.U;if(b instanceof Xg){a.a=b;a.a.d=a;dh(a.a,a.Aa)}else{c||(b=Yg(b,eh));a.a=new Xg(b,a,a.Aa)}return a}
function fh(a,b,c){ch(a);delete a.U;R(c)||(c=[ha(c)]);var d=a.a;b=b;c=c;gh(d);hh(d);b=ih(d,b);if(d.ja(b)){var e=d.w.N(b);if(R(e))d.p-=e[x];else d.p--}if(c[x]>0){d.w.ea(b,c);d.p+=c[x]}return a}function Wg(a,b,c){ch(a);delete a.U;a.Ua=c?b?ja(b):"":b;return a}function ch(a){if(a.Ed)g(aa("Tried to modify a read-only Uri"))}function Pg(a,b){a.Aa=b;a.a&&dh(a.a,b)}function $g(a){if(S(a))return da(a);return j}var jh=/^[a-zA-Z0-9\-_.!~*'():\/;?]*$/;
function Yg(a,b){var c=j;if(S(a)){c=a;jh[Ha](c)||(c=encodeURI(a));if(c.search(b)>=0)c=c[A](b,kh)}return c}function kh(a){a=a.charCodeAt(0);return"%"+(a>>4&15)[v](16)+(a&15)[v](16)}var Zg=/[#\/\?@]/g,ah=/[\#\?]/g,eh=/[\#\?@]/g,bh=/#/g;function Xg(a,b,c){this.a=a||j;this.d=b||j;this.c=!!c}
function gh(a){if(!a.w){a.w=new Ig;if(a.a)for(var b=a.a[Ua]("&"),c=0;c<b[x];c++){var d=b[c][C]("="),e=j,f=j;if(d>=0){e=b[c][yb](0,d);f=b[c][yb](d+1)}else e=b[c];e=ja(e[A](/\+/g," "));e=ih(a,e);a.add(e,f?ja(f[A](/\+/g," ")):"")}}}P=Xg[y];P.w=j;P.p=j;P.add=function(a,b){gh(this);hh(this);a=ih(this,a);if(this.ja(a)){var c=this.w.N(a);R(c)?c[s](b):this.w.ea(a,[c,b])}else this.w.ea(a,b);this.p++;return this};
P.remove=function(a){gh(this);a=ih(this,a);if(this.w.ja(a)){hh(this);var b=this.w.N(a);if(R(b))this.p-=b[x];else this.p--;return this.w.remove(a)}return k};P.clear=function(){hh(this);this.w&&this.w.clear();this.p=0};P.ja=function(a){gh(this);a=ih(this,a);return this.w.ja(a)};P.ya=function(){gh(this);for(var a=this.w.qa(),b=this.w.ya(),c=[],d=0;d<b[x];d++){var e=a[d];if(R(e))for(var f=0;f<e[x];f++)c[s](b[d]);else c[s](b[d])}return c};
P.qa=function(a){gh(this);if(a){a=ih(this,a);if(this.ja(a)){var b=this.w.N(a);if(R(b))return b;else{a=[];a[s](b)}}else a=[]}else{b=this.w.qa();a=[];for(var c=0;c<b[x];c++){var d=b[c];R(d)?Cc(a,d):a[s](d)}}return a};P.ea=function(a,b){gh(this);hh(this);a=ih(this,a);if(this.ja(a)){var c=this.w.N(a);if(R(c))this.p-=c[x];else this.p--}this.w.ea(a,b);this.p++;return this};P.N=function(a,b){gh(this);a=ih(this,a);if(this.ja(a)){a=this.w.N(a);return R(a)?a[0]:a}else return b};
ka(P,function(){if(this.a)return this.a;if(!this.w)return"";for(var a=[],b=0,c=this.w.ya(),d=0;d<c[x];d++){var e=c[d],f=Tc(e);e=this.w.N(e);if(R(e))for(var h=0;h<e[x];h++){b>0&&a[s]("&");a[s](f,"=",Tc(e[h]));b++}else{b>0&&a[s]("&");a[s](f,"=",Tc(e));b++}}return this.a=a[N]("")});function hh(a){delete a.b;delete a.a;a.d&&delete a.d.U}Xg[y].L=function(){var a=new Xg;if(this.b)a.b=this.b;if(this.a)a.a=this.a;if(this.w)a.w=this.w.L();return a};
function ih(a,b){b=ha(b);if(a.c)b=b.toLowerCase();return b}function dh(a,b){var c=b&&!a.c;if(c){gh(a);hh(a);Hg(a.w,function(d,e){var f=e.toLowerCase();if(e!=f){this.remove(e);this.add(f,d)}},a)}a.c=b};function lh(a,b){this.b=new Og(a);this.a=b?b:"callback";this.Ka=5E3}var mh=0;
va(lh[y],function(a,b,c,d){if(!ia[Ob][I]){c&&c(a);return j}d=d||"_"+(mh++)[v](36)+cc()[v](36);Q._callbacks_||(Q._callbacks_={});var e=W[H]("script"),f=j;if(this.Ka>0){f=nh(d,e,a,c);f=Q[Sa](f,this.Ka)}c=this.b.L();a=a;var h=c;for(var n in a)if(!a[ab]||a[ab](n))fh(h,n,a[n]);if(b){b=oh(d,e,b,f);Q._callbacks_[d]=b;fh(c,this.a,"_callbacks_."+d)}W.pb(e,{type:"text/javascript",id:d,charset:"UTF-8",src:c[v]()});W[p](ia.getElementsByTagName("head")[0],e);return{R:d,Ka:f}});
oa(lh[y],function(a){if(a&&a.R){var b=W.l(a.R);if(b&&b[K]=="SCRIPT"&&typeof Q._callbacks_[a.R]=="function"){a.Ka&&Q[La](a.Ka);ph(a.R,b,k)}}});function nh(a,b,c,d){return function(){ph(a,b,k);d&&d(c)}}function oh(a,b,c,d){return function(){Q[La](d);ph(a,b,i);c[Fb](ca,arguments)}}function ph(a,b,c){Q[Sa](function(){W[Bb](b)},0);if(Q._callbacks_[a])if(c)delete Q._callbacks_[a];else Q._callbacks_[a]=Sb};function qh(a,b){this.c=new Og(a);if(b)for(var c in b)b[c]!==m[y][c]&&rh(this,c,b[c])}U(qh,uc);function rh(a,b,c){a=a.c;b=b;c=c;ch(a);delete a.U;a.a.ea(b,c)}wa(qh[y],function(){return i});va(qh[y],function(){return j});oa(qh[y],function(){});function sh(a,b,c){qh[G](this,a,b);this.a=new lh(this.c[v](),c)}U(sh,qh);va(sh[y],function(a,b){this.a.Ka=-1;return this.a[ob](a,b)});oa(sh[y],function(a){this.a[Pa](a)});
function th(a,b,c){qh[G](this,"",c);this.d=a;this.e=b;this.g=Pf(c);this.b={};Q._fhr_callback_||(Q._fhr_callback_={});this.d=a}U(th,qh);var uh=0;function vh(){return"I"+(uh++)[v](36)+cc()[v](36)}function wh(a){if(!a.k){a.k=W.z("div",{style:"position:absolute;top:-1000px;height:1px;width:1px"});W.o()[E][p](a.k);a.R="f"+vh();var b={id:a.R,src:a.d};pa(a.k,yf(b))}if(!a.a)a.a=V?l[a.R]:W.o()[a.R]}wa(th[y],function(){wh(this);return this.a&&this.a[sb]&&this.a[sb]()});
va(th[y],function(a,b){wh(this);if(!this.a||!this.a[ob])return j;var c="cb"+vh();Q._fhr_callback_[c]=b;a=this.a[ob](this.e,"_fhr_callback_."+c,this.g,Pf(a));if(a<0){delete Q._fhr_callback_[c];return j}b=vh();this.b[b]={Vc:c,ha:a};return b});oa(th[y],function(a){wh(this);var b=this.b[a];if(b){this.a[Pa](b.ha);delete Q._fhr_callback_[b.Vc];delete this.b[a]}});
th[y].D=function(){th.A.D[G](this);for(var a in this.b)if(this.b[a]!==m[y][a]){var b=this.b[a];this.a[Pa](b.ha);delete Q._fhr_callback_[b.ha]}if(this.k){W[Bb](this.k);this.a=this.b=this.k=j}};function xh(a){var b={anno:3,client:ic,format:"html",v:"1.0"};a&&(b.ssl=1);a=a?"https://":"http://";this.a={T:new th(a+lc,"translate",b),xb:yh,Ic:30720,Jd:61440,Id:-1,Vd:0,zb:k};this.b={T:this.a.T,xb:zh,Hc:300};this.c=new sh(a+mc,{client:ic},"cb")}U(xh,uc);
function yh(a){return function(b){if(b)try{var c=eval("("+b+")")}catch(d){c=j}if(c){if(Ub(c)!="array")b=[[c,200]];else if(Ub(c[0])!="array")if(c[x]==2)b=[[c[0],200,c[1]],[c[1],200,c[1]]];else{b=[];for(var e=0;e<c[x];++e)b[e]=[c[e],200]}else{b=[];for(e=0;e<c[x];++e)b[e]=[c[e][0],200,c[e][1]]}a(b,200)}else a([],500)}}function zh(a){return function(b){if(b)try{var c=eval("("+b+")")}catch(d){c=j}a(c&&c[1]||ca)}}wa(xh[y],function(){return this.b.T[sb]()&&this.a.T[sb]()});
xh[y].translate=function(a,b,c,d,e,f){a=this.a.xb(a);b={q:b,sl:c,tl:d};b.tc=e;if(f)b.ctt=1;return this.a.T[ob](b,a)};xh[y].D=function(){xh.A.D[G](this);this.a.T.t();this.a.T=j;this.b.T.t();this.b.T=j;this.c.t();this.c=j};function Ah(a,b){this.d=a;this.k=!!b;this.a=this.j=0;this.b=this.c=-1;this.e=this.h=this.g=0}var Bh=Bf([".",",",";",":","\\?","!"]),Ch=Bf([34,35,36,37,38,43,44,47,58,59,60,61,62,63,64,91,92,93,94,96,123,124,125,127]);function Dh(a,b){if(!a.k)return 1;if(b<=127){if(b<=32||Ch[b])return 3;return 1}else if(b<=2047)return 6;else if(b<=65535)return 9;return 12}
function Eh(a,b){a.k&&(b-=12);for(var c="",d=a.j;d<a.d[x];++d){var e=a.d.charAt(d),f=e.charCodeAt(0);a.g+=Dh(a,f);if(Bh[e]){a.b=d;a.h=a.g}else if(e==" "){a.c=d;a.e=a.g}if(a.g>=b){if(a.b>=0){c=a.d[yb](a.a,a.b+1);a.g-=a.h;a.a=a.b+1;if(a.b>=a.c){a.c=-1;a.e=0}else a.e-=a.h;a.b=-1;a.h=0}else if(a.c>=0){c=a.d[yb](a.a,a.c+1);a.g-=a.e;a.a=a.c+1;if(a.c>=a.b)a.b=-1;else a.h-=a.e;a.c=-1;a.e=0}else{c=a.d[yb](a.a,d+1);a.g=0;a.a=d+1;a.b=a.c=-1;a.e=a.h=0}a.j=d+1;return c}}if(a.a<a.d[x]){c=a.d[yb](a.a);a.a=a.d[x]}return c}
function Fh(a,b){this.B=b;this.Y=new qg(T(this.Tc,this),b);this.c=j;this.K=k;this.s="auto";this.g="en";this.Na=k;this.a=new xh(a)}U(Fh,uc);wa(Fh[y],function(){return this.a[sb]()});
Fh[y].Uc=function(a,b,c,d){function e(){var ga=k;if(h<n){h*=6;if(h>n)h=n;ga=i}var gg=q+1024;if(h>gg){h=gg;ga=i}return ga}if(a!=this.s||b!=this.g)this[Pa]();else if(this.he)return;this.r=c;this.e=[0];this.La=this.ia=this.db=0;if(this.c){this.d=new Cf(0,20);this.e=[0];var f=0;for(a=0;a<this.c[x];++a){this.d.add(T(this.wa,this,this.c[a]));b=o[Qa](a*100/this.c[x]);this.e[s](f==b?-1:b);f=b}this.d.add(T(this.Ma,this));Gh(this);this.d.go()}else{this.d=new Cf(0,4);this.K=i;this.s=a;this.g=b;this.B&&Vf(this.B,
a,b);this.b=[];this.c=[];this.G=this.k=0;this.h=[];this.I=[];this.j={};var h=860;a=h;var n=this.a.a.zb?this.a.a.Ic-this.a.a.T.c.L()[v]()[x]:this.a.a.Ic,q=this.a.a.Jd;b=0;c=this.a.a.Id;var r=this.a.a.zb;this.Y.reset(d||W.o()[Ob],r);for(d=j;q>0&&(f=wg(this.Y,h));){this.c[s](f);r=this.a.a.zb?f.r:f.yb[x];if(r>h){r=f.yb;var t=new Ah(r),w=[],u="";for(d&&e();u=Eh(t,h);){var sa={ha:j,dd:f,Ba:w,content:u,Za:k};w[s](sa);this.b[s](sa);q-=u[x];if(e()&&q<=0){sa.ec=r[yb](t.a);break}}}else{if(!d||r>a||b>=c&&c>0){if(d){Hh(this);
e();a=h}d={ha:j,fa:[],Za:k};this.b[s](d);b=0}d.fa[s](f);a-=r+this.a.a.Vd;q-=r;b++}}Hh(this);if(!this.b[x]){this.K=k;this.r(100,i)}}};Fh[y].Tc=function(a){var b=Pc(a[xb]);if(!(b[C]("javascript:")==0||b[C]("#")>=0)){this.I[s](a[xb]);this.h[s](a);ya(a,b+"#googtrans/"+this.s+"/"+this.g)}};
function Hh(a){for(var b=3+a.k;a.G<a.b[x]&&a.G<b;++a.G){var c=a,d=a.G,e=c.b[d],f=e.Mc||c.s,h=[];if(e.fa)for(var n=0;n<e.fa[x];++n)h[s](e.fa[n].yb);else h[s](e.content);e.ha=c.a.translate(T(c.ub,c,d),h,f,c.g,d+1,c.Na)}}
Fh[y].ub=function(a,b,c){if(c!=200){this.k++;a=this.k==this.b[x];b=o[Qa](this.k*100/this.b[x]);this.r(b,a,i)}else{c=this.b[a];if(this.K&&c){if(c.fa){var d=[];for(a=0;a<b[x]&&a<c.fa[x];++a)if(b[a]&&b[a][1]&&b[a][1]==200){var e=b[a][0];this.d.add(T(this.wa,this,c.fa[a],e));this.e[s](0);if(b[a][2]){var f=b[a][2];this.j[f]||(this.j[f]=0);this.j[f]+=e[x]}}else d[s](c.fa[a]);this.s=="auto"&&d[x]>0&&!c.Za&&this.b[s]({ha:j,Mc:"en",fa:d,Za:i})}else if(b&&b[0]){c.Oc=b[0][0];if(b[0][2]){f=b[0][2];if(this.j[f])this.j[f]=
0;this.j[f]=b[0][0][x]}b=[];for(a=0;a<c.Ba[x];++a)if(typeof c.Ba[a].Oc=="string"){b[s](c.Ba[a].Oc);c.Ba[a].ec&&b[s](c.Ba[a].ec)}else break;if(b[x]==c.Ba[x]){this.d.add(T(this.wa,this,c.dd,b[N]("")));this.e[s](0)}}else if(this.s=="auto"&&!c.Za){c.Mc="en";c.Za=i;c.ha=j;this.b[s](c)}this.k++;this.k==this.b[x]&&this.d.add(T(this.Ma,this));b=this.La;this.La=o[Qa](this.k*100/this.b[x]);c=this.e[x]-this.ia-1;if(c>0){d=b;a=this.ia+1;for(e=1;a<this.e[x];++a,++e){f=o[Qa]((this.La-b)/c*e+b);if(f==d)this.e[a]=
-1;else d=this.e[a]=f}this.ia=this.e[x]-1}this.d.go();Hh(this)}}};Fh[y].wa=function(a,b){b?dg(a,b):eg(a);a=this.e[++this.db];a>=0&&this.r(a,k)};Fh[y].Ma=function(){this.K=k;this.r&&this.r(100,i);this.r=this.b=j;this.G=this.k=0;this.e=j;this.ia=this.db=0};function Gh(a){if(a.h)for(var b=0;b<a.h[x];++b){var c=a.h[b][xb];ya(a.h[b],a.I[b]);a.I[b]=c}}Fh[y].restore=function(){if(this.c)for(var a=0;a<this.c[x];++a)this.c[a][Cb]();Gh(this);this.B&&Yf(this.B)};
oa(Fh[y],function(){if(this.K){for(var a=0;a<this.b[x];++a)this.a.a.T[Pa](this.b[a].ha);this.Ma()}if(this.d){this.d[Pa]();this.d=j}if(this.c){for(a=0;a<this.c[x];++a)this.c[a].t();this.c=j}this.B&&Yf(this.B);if(this.h){for(a=0;a<this.h[x];++a)ya(this.h[a],this.I[a]);this.I=this.h=j}if(this.j)this.j=j});Fh[y].D=function(){Fh.A.D[G](this);this[Pa]();this.Y=j;this.a.t();this.a=j};function Ih(a,b){if(Ub(a)=="string"){b=a;a={}}if(Ub(b)=="string")b=W.l(ha(b));this.k=b;a=m(a);this.d="auto";this.a={vb:(!l.external||!l.external.googleToolbarVersion||fa(l.external.googleToolbarVersion)<6.2)&&(!l.gtbExternal||!l.gtbExternal.isTranslateEnabled||!l.gtbExternal.isTranslateEnabled()),wb:j,fb:j,Mb:[],Ab:[],cd:k,Rb:k,tb:k};b=l[Ya].protocol=="https:";this.La={C:pc,va:b?"El contenido de esta p\u00e1gina segura se enviar\u00e1 a Google para traducirlo con una conexi\u00f3n segura.":j};this.a.tb=
b;this.Y={C:pc,Ta:j};if(a){"autoDisplay"in a&&(this.a.vb=ba(a.autoDisplay));"multilanguagePage"in a&&(this.a.Rb=ba(a.multilanguagePage));if(a.pageLanguage)this.a.Sb=Of(a.pageLanguage);if("useSecureConnection"in a){this.a.tb=!!a.useSecureConnection;this.La.va=this.a.tb?"El contenido de esta p\u00e1gina segura se enviar\u00e1 a Google para traducirlo con una conexi\u00f3n segura.":j}if(a.includedLanguages)this.a.Mb=a.includedLanguages[Ua](",");if(a.excludedLanguages)this.a.Ab=a.excludedLanguages[Ua](",");
if(this.a.Sb){this.d=this.a.Sb;this.a.Rb||this.a.Ab[s](this.d)}this.Y.Ta=Number(a.floatPosition)||this.Y.Ta}if((a=l[Ya][xb].match(/#.*googtrans(.*)/))&&a[1])if(a=ja(a[1][A](/\+/g," ")).match("^\\((([a-zA-Z\\-_]*)\\|)?([a-zA-Z\\-_]*)\\)|^/(([a-zA-Z\\-_]*)/)?([a-zA-Z\\-_]*)"))if(a[3]){this.a.wb=a[2];this.a.fb=a[3]}else if(a[6]){this.a.wb=a[5];this.a.fb=a[6]}a={formMode:0,showLogo:i,suggestUrl:"http://translate.google.com/translate_suggestion",clientName:ic,pageUrl:l[Ya][xb]};this.ub=new Uf(a);this.e=
new Fh(this.a.tb,this.ub);this.h=new cf(this);this.G=this.wa=k;this.Ma=!this.a.vb&&!this.Y.Ta&&!this.k;Y(this.h,l,"unload",this.t);this.B=new Df(T(this.wd,this));this.s=new Df(T(this.yd,this));this.I=new Hf(T(this.Fd,this));a=Ef(this.B,T(this.vd,this));this.e.a.c[ob](ec?{hl:ec}:{},a);this.b=new zg(this.La);if(this.k){this.c=new Dg;Y(this.h,this.c,"load",Ef(this.B));Y(this.h,this.c,"chg_tgt_lang",If(this.I,Gf(this.s,T(this.ud,this))));this.c.la(this.k)}else if(this.Y.Ta){this.j=new Eg(this.Y);Y(this.h,
this.j,"load",Ef(this.B));Y(this.h,this.j,"clk_trans",If(this.I,Gf(this.s,T(this.sd,this))));this.j.la()}if(!this.a.Sb&&this.a.cd){this.ia=new Jf(T(this.e[sb],this.e),Ef(this.B,T(this.Cc,this,i)),0,300);this.ia.go()}this.B.Sa()}U(Ih,uc);function Jh(a,b,c){try{if(Ub(b)=="function")return b[Fb](a,c||[])}catch(d){}}P=Ih[y];
P.Cc=function(a,b){this.ia=j;if(this.wa=b)if(a){b=this.e;a=Ef(this.B||this.s,T(this.qd,this));var c=W.o()[Ob].lang;if(c)a(c);else{var d=new og(W.o()[E],k,k,1,1);c=[];try{for(var e=0,f=b.a.b.Hc;c[x]+e<f;){var h=d.c();if(d.S==1&&yg(b.Y,h))pg(d);else if(h[B]==3){var n=Pc(h[Nb][A](/\xa0|[ \t]+/g," "));if(n){c[s](n);e+=n[x]}}}}catch(q){if(q!=mg)g(q)}f=b.a;h=c[N](" ");a=f.b.xb(a);h={q:h[yb](0,f.b.Hc)};h.sl="auto";h.tl="en";f.b.T[ob](h,a)}}};
P.vd=function(a){this.g=Of(ec);this.K=a||{};this.r={};a=!this.a.Mb[x];var b=Bf(this.a.Mb),c=Bf(this.a.Ab);this.r[ec]="";for(var d in this.K.tl)if(this.K.tl[d]!==m[y][d])if((a||d in b)&&!(d in c))this.r[d]=this.K.tl[d];this.r[ec]||delete this.r[ec];var e;d=this.K.sl;a={};for(e in d)a[e]=d[e];this.Na=e=a};P.qd=function(a){if(a)this.d=Of(a)};
P.wd=function(){delete this.B;if(this.K){this.d=this.a.wb||this.d;this.g=this.a.fb||this.g;var a=this.a.vb&&this.d!=this.g&&!(this.d in hc);if(this.d=="zh-TW")this.d="zh-CN";if(!this.Na[this.d]){a=k;this.d="auto"}if(!this.r[this.g]){a=k;if(this.r.en)this.g="en";else for(var b in this.r)if(this.r[b]!==m[y][b]){this.g=b;break}}if(this.c){var c=this.r,d={"":"Seleccionar idioma"};for(b in c)if(c[b]!==m[y][b])d[b]=c[b];this.c.Ub(d);this.c.aa("")}if(!gc&&this.a.fb)If(this.I,Gf(this.s,T(this.qb,this,i,i)))[G]();
else if(!gc&&a){this.G=i;If(this.I,Gf(this.s,T(this.qb,this)))[G]();Qf("te_ap",{sl:this.d})}else{this.j&&this.j.O(i);this.c&&this.c.O(i)}this.I.Sa()}};
P.yd=function(){var a=this.b,b=this.Na;a.H&&a.H.$a(b);a.j=b;this.b.Ub(this.r);Ag(this.b,this.d);this.b.aa(this.g);Y(this.h,this.b,"clk_confirm",this.nd);Y(this.h,this.b,"clk_cancel",this.md);Y(this.h,this.b,"clk_restore",this.pd);Y(this.h,this.b,"clk_close",this.Ec);Y(this.h,this.b,"clk_no_ap",this.od);Y(this.h,this.b,"chg_src_lang",this.Dc);Y(this.h,this.b,"chg_tgt_lang",this.Dc);this.c&&this.c.O(i)};
P.Fd=function(){Y(this.h,this.b,"load",Ef(this.s));this.b.la();if(!this.wa){this.ia=new Jf(T(this.e[sb],this.e),Ef(this.s,T(this.Cc,this,k)),0,300);this.ia.go()}this.s.Sa()};P.D=function(){this.e[Pa]();Ih.A.D[G](this);this.e.t();this.h.t();this.h=j;this.b&&this.b.t();this.b=j;this.j&&this.j.t();this.j=j;this.c&&this.c.t();this.k=this.c=j};P.nd=function(){if(this.b.ca()){this.G&&Qf("te_apt",{sl:this.d});Kh(this,k);this.c&&this.c.aa(this.b.za())}};
P.md=function(){if(this.b.ca()){l[Sa](T(this.e[Pa],this.e),0);Bg(this.b,0);this.c&&this.c.aa("")}};P.pd=function(){if(this.b.ca()){l[Sa](T(this.e[Cb],this.e),0);Bg(this.b,0);this.c&&this.c.aa("")}};P.Ec=function(){if(this.b.ca()){if(this.G){this.G=k;Qf("te_apc",{sl:this.d})}l[Sa](T(this.e[Cb],this.e),0);this.b.O(k);this.c&&this.c.aa("");this.j&&this.j.O(i)}};P.od=function(){if(this.b.ca()){Qf("te_apr",{sl:this.d});this.G=k;this.Ec();this.Ma&&Jh(this,this.onTurnOffLanguageClick)}};
P.Dc=function(){if(this.b.ca()){this.d=(this.b.H?this.b.H.lb():"")||this.d;this.g=this.b.za();if(this.b.Qa==2){this.c&&this.c.aa(this.b.za());Kh(this)}}};P.qb=function(a,b){if(!this.b.ca()){this.j&&this.j.O(k);a?Kh(this,b):Bg(this.b,0,i,this.G||this.Ma)}};P.Wd=function(a,b){If(this.I,Gf(this.s,T(this.qb,this,a,b)))[G]()};P.sd=function(){this.qb(this.b.Qa==2)};P.ud=function(){if(this.c.za()){this.g=this.c.za();this.b.aa(this.g);Kh(this)}else this.c.aa(this.g)};
function Kh(a,b){a.G=k;!b&&a.d in hc&&Qf("te_ape",{sl:a.d});if(a.wa){Cg(a.b,0);Bg(a.b,1,i);a.e.Na=!!b;l[Sa](T(a.e.Uc,a.e,a.a.Rb?"auto":a.d,a.g,T(a.db,a),j),0)}else Bg(a.b,-1,i)}Ih[y].db=function(a,b,c){if(!(!this.b.ca()||this.b.Qa!=1))if(c){l[Sa](T(this.e[Pa],this.e),0);Bg(this.b,-1,i)}else{Cg(this.b,a);if(b){this.c&&this.c.aa(this.g);Ag(this.b,this.d);Bg(this.b,2)}}};Qb("google.translate.TranslateElement",Ih,void 0);Ih[y].dispose=Ih[y].t;Ih[y].showBanner=Ih[y].Wd;
Qb("google.translate.TranslateElement.FloatPosition",Fg,void 0);Fg.TOP_LEFT=1;Fg.TOP_RIGHT=2;Fg.BOTTOM_RIGHT=3;Fg.BOTTOM_LEFT=4;(function(){for(var a in m[y]){Ic=function(c,d,e){for(var f in c)c[f]!==m[y][f]&&d[G](e,c[f],f,c)};break}var b=cc();l[fc]&&Ub(l[fc])=="function"&&function c(){var d=ia.readyState;Ub(d)=="undefined"||d=="complete"||cc()-b>=2E4?l[fc]():l[Sa](c,500)}()})();})()
